-- Generated by KernelPacker
--  29 modules detected, 0 files kept same but concatenated
--
-- missing assets couldnt be downloaded or not found
-- Listed :
--   "Reanimated.anim" needed by module "Reanimated"
--   "Wait!.anim" needed by module "Wait"
--   "Wait!.mp3" needed by module "Wait"
--   "All my fellas.mp3" needed by module "All my fellas"
--   "Chinese dance.mp3" needed by module "Chinese dance"
--   "Heya!.anim" needed by module "Heya!"
--   "Loli dance.mp3" needed by module "Loli dance"
--   "the hero.mp3" needed by module "the hero"
--   "Caramell.mp3" needed by module "Caramell"
--   "Secret.mp3" needed by module "Secret"
--   "Wipe me down.mp3" needed by module "Wipe me down"
--   "Fresh.anim" needed by module "Fresh"
--   "Spooky month.anim" needed by module "Spooky month"
--   "Spooky month.mp3" needed by module "Spooky month"

local modules = {}

local dances = {
    -- from: Goopie.lua
    {
        name        = "Goopie",
        desc        = "Bro moves like a HT character, Lmao",
        anim        = "Goopie.anim@MARKET/MARKET_n1ghtEpikDances/assets/WrcKDuVk_Goopie.anim",
        song        = "Goopie.mp3@MARKET/MARKET_n1ghtEpikDances/assets/tttindSP_Goopie.mp3",
        musicName   = "shucks",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Moongazer.lua
    {
        name        = "Moon gazer",
        desc        = "Where tf is this from",
        anim        = "Moongazer.anim@MARKET/MARKET_n1ghtEpikDances/assets/qg7MNKCS_Moongazer.anim",
        song        = "Moongazer.mp3@MARKET/MARKET_n1ghtEpikDances/assets/oJsFBjun_Moongazer.mp3",
        musicName   = "shucks",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: summer.lua
    {
        name        = "Summer",
        desc        = "かなり暑い夏です😮‍💨",
        anim        = "Summer.anim@MARKET/MARKET_n1ghtEpikDances/assets/AvV1NFc6_Summer.anim",
        song        = "Summer.mp3@MARKET/MARKET_n1ghtEpikDances/assets/YtdauVPL_Summer.mp3",
        musicName   = "Summer",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Reanimated.lua
    {
        name        = "Reanimated",
        desc        = "What i see the homeless man doing after i Give him some money",
        anim        = "Reanimated.anim",
        song        = "Reanimated.mp3@MARKET/MARKET_n1ghtEpikDances/assets/ZKnCkNjy_Reanimated.mp3",
        musicName   = "NUMBER",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Boppin.lua
    {
        name        = "Boppin",
        desc        = "Tuff demon dance bro",
        anim        = "Boppin.anim@MARKET/MARKET_n1ghtEpikDances/assets/nz3MJmZ7_Boppin.anim",
        song        = "Boppin.mp3@MARKET/MARKET_n1ghtEpikDances/assets/FLXigXd2_Boppin.mp3",
        musicName   = "shucks",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Mannrobics.lua
    {
        name        = "Mannrobics",
        desc        = "Tf2 reference?!",
        anim        = "Mannrobics.anim@MARKET/MARKET_n1ghtEpikDances/assets/gg2y1F7R_Mannrobics.anim",
        song        = "Mannrobics.mp3@MARKET/MARKET_n1ghtEpikDances/assets/flhnWoM7_Mannrobics.mp3",
        musicName   = "Mannrobics",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Wait!.lua
    {
        name        = "Wait",
        desc        = "They don't love you like i do..",
        anim        = "Wait!.anim",
        song        = "Wait!.mp3",
        musicName   = "Wait!",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: cha.lua
    {
        name        = "Cha cha cha",
        desc        = "CHA CHA CHAAAAAAAA",
        anim        = "Cha.anim@MARKET/MARKET_n1ghtEpikDances/assets/MDJjNxgi_Cha.anim",
        song        = "Cha.mp3@MARKET/MARKET_n1ghtEpikDances/assets/61raOu2S_Cha.mp3",
        musicName   = "Cha",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Pug.lua
    {
        name        = "Pug",
        desc        = "Cute lil pug ",
        anim        = "Pug.anim@MARKET/MARKET_n1ghtEpikDances/assets/AThpme4q_Pug.anim",
        song        = "Pug.mp3@MARKET/MARKET_n1ghtEpikDances/assets/naD8md5Y_Pug.mp3",
        musicName   = "parrot party",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Dancin.lua
    {
        name        = "Dancin",
        desc        = "Cant you see, honey you were for me, oh we were meant to b-e-e-e-e",
        anim        = "Dancin.anim@MARKET/MARKET_n1ghtEpikDances/assets/HD7k0ctW_Dancin.anim",
        song        = "Dancin.mp3@MARKET/MARKET_n1ghtEpikDances/assets/3IWI2Mqq_Dancin.mp3",
        musicName   = "Dancin",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: boogie.lua
    {
        name        = "Boogie",
        desc        = "Boogieing down?",
        anim        = "Boogie.anim@MARKET/MARKET_n1ghtEpikDances/assets/tvDGywWL_Boogie.anim",
        song        = "Boogie.mp3@MARKET/MARKET_n1ghtEpikDances/assets/wnJIrDvW_Boogie.mp3",
        musicName   = "Boogie",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: all my fellas.lua
    {
        name        = "All my fellas",
        desc        = "THIS WAS THE SONG OF 2023.",
        anim        = "Allmyfellas.anim@MARKET/MARKET_n1ghtEpikDances/assets/6s6WunGm_Allmyfellas.anim",
        song        = "All my fellas.mp3",
        musicName   = "All my fellas",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Chinese dance.lua
    {
        name        = "Chinese dance",
        desc        = "Subject 4?!",
        anim        = "Chinesedance.anim@MARKET/MARKET_n1ghtEpikDances/assets/VsSL46Zo_Chinesedance.anim",
        song        = "Chinese dance.mp3",
        musicName   = "Chinese dance",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: doodle.lua
    {
        name        = "Doodle",
        desc        = "Da doodle sahoor",
        anim        = "Doodle.anim@MARKET/MARKET_n1ghtEpikDances/assets/srSQNCp7_Doodle.anim",
        song        = "Doodle.mp3@MARKET/MARKET_n1ghtEpikDances/assets/PXD4oYQk_Doodle.mp3",
        musicName   = "Doodle",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: heya!.lua
    {
        name        = "Heya!",
        desc        = "Thank god for mom and dad for sticking two together cuz we dont know howw- wait what",
        anim        = "Heya!.anim",
        song        = "Heya.mp3@MARKET/MARKET_n1ghtEpikDances/assets/fL4zYyJI_Heya.mp3",
        musicName   = "Heya!",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: loli dance.lua
    {
        name        = "Loli dance",
        desc        = "Cringe as hell, i know :/",
        anim        = "Lolidance.anim@MARKET/MARKET_n1ghtEpikDances/assets/QrhIo5UG_Lolidance.anim",
        song        = "Loli dance.mp3",
        musicName   = "Loli dance",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Fright funk.lua
    {
        name        = "Fright funk",
        desc        = "Dancing in season 6 with this was peak",
        anim        = "Frightfunk.anim@MARKET/MARKET_n1ghtEpikDances/assets/mCkX2xUG_Frightfunk.anim",
        song        = "Frightfunk.mp3@MARKET/MARKET_n1ghtEpikDances/assets/klAyahGf_Frightfunk.mp3",
        musicName   = "shucks",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: the hero.lua
    {
        name        = "the hero",
        desc        = "Spanish rap goes hard",
        anim        = "thehero.anim@MARKET/MARKET_n1ghtEpikDances/assets/QyCEWaaC_thehero.anim",
        song        = "the hero.mp3",
        musicName   = "the hero",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: step.lua
    {
        name        = "Step",
        desc        = "Walking through 2fort till you get sho",
        anim        = "Step.anim@MARKET/MARKET_n1ghtEpikDances/assets/rg9FbT9n_Step.anim",
        song        = "Step.mp3@MARKET/MARKET_n1ghtEpikDances/assets/kh8cFSGN_Step.mp3",
        musicName   = "Step",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: caramell.lua
    {
        name        = "Caramell",
        desc        = "Sweedish war thunder rat tank🥶🥶",
        anim        = "Caramell.anim@MARKET/MARKET_n1ghtEpikDances/assets/37a1cG4S_Caramell.anim",
        song        = "Caramell.mp3",
        musicName   = "Caramell",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: secret.lua
    {
        name        = "Secret",
        desc        = "What is diddy blud saying",
        anim        = "Secret.anim@MARKET/MARKET_n1ghtEpikDances/assets/3vkPvjgM_Secret.anim",
        song        = "Secret.mp3",
        musicName   = "Secret",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Wipe me down.lua
    {
        name        = "Wipe me down",
        desc        = "Cold n-(going to stop here obviously)",
        anim        = "Wipemedown.anim@MARKET/MARKET_n1ghtEpikDances/assets/pfgqWdB4_Wipemedown.anim",
        song        = "Wipe me down.mp3",
        musicName   = "Wipe me down",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: insanity.lua
    {
        name        = "Insanity",
        desc        = "Dancing like a Egg bro💔",
        anim        = "Insanity.anim@MARKET/MARKET_n1ghtEpikDances/assets/lz5OfBp6_Insanity.anim",
        song        = "Insanity.mp3@MARKET/MARKET_n1ghtEpikDances/assets/ypYyUQgN_Insanity.mp3",
        musicName   = "Insanity",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Take the L.lua
    {
        name        = "Take the L",
        desc        = "Losseeeeerrrrrr",
        anim        = "TaketheL.anim@MARKET/MARKET_n1ghtEpikDances/assets/bpswyy7N_TaketheL.anim",
        song        = "TaketheL.mp3@MARKET/MARKET_n1ghtEpikDances/assets/Bd1mgsgp_TaketheL.mp3",
        musicName   = "Take the L",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: rakuten lemonade.lua
    {
        name        = "Rakuten lemonade",
        desc        = "レモネードが好きです！",
        anim        = "Rakutenlemonade.anim@MARKET/MARKET_n1ghtEpikDances/assets/Pb1SDhOZ_Rakutenlemonade.anim",
        song        = "Rakutenlemonade.mp3@MARKET/MARKET_n1ghtEpikDances/assets/uAoehsRg_Rakutenlemonade.mp3",
        musicName   = "Rakuten lemonade",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: rat.lua
    {
        name        = "rat dance",
        desc        = "Who knew the rat has moves?",
        anim        = "rat.anim@MARKET/MARKET_n1ghtEpikDances/assets/H8D5uAGU_rat.anim",
        song        = "rat.mp3@MARKET/MARKET_n1ghtEpikDances/assets/Bx6HNcVq_rat.mp3",
        musicName   = "rat dance kdv3",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: fresh.lua
    {
        name        = "Fresh",
        desc        = "When a gardener plants a watermelon",
        anim        = "Fresh.anim",
        song        = "Fresh.mp3@MARKET/MARKET_n1ghtEpikDances/assets/eM8FRNuc_Fresh.mp3",
        musicName   = "Fresh",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: spooky month.lua
    {
        name        = "Spooky month",
        desc        = "When its October",
        anim        = "Spooky month.anim",
        song        = "Spooky month.mp3",
        musicName   = "Spooky month",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: LMC.lua
    {
        name        = "Lemon melon cookie",
        desc        = "This was a trend ig",
        anim        = "LMC.anim@MARKET/MARKET_n1ghtEpikDances/assets/bIeiZWpw_LMC.anim",
        song        = "LMC.mp3@MARKET/MARKET_n1ghtEpikDances/assets/SQqcgWWH_LMC.mp3",
        musicName   = "Lemon melon cookie",
        volume      = 0.8,
        configText  = "No settings.",
    },
}

for i = 1, #dances do
    local d = dances[i]
    table.insert(modules, function()
        local m = {}
        local animator = nil
        local start = 0

        m.ModuleType  = "DANCE"
        m.Name        = d.name
        m.Description = d.desc
        m.Assets      = {d.anim, d.song}

        m.Config = function(parent)
            Util_CreateText(parent, d.configText, 14, Enum.TextXAlignment.Center)
        end

        m.SaveConfig = function() return {} end
        m.LoadConfig = function(save) end

        m.Init = function(figure)
            SetOverrideDanceMusic(AssetGetContentId(d.song:match("^[^@]+")), d.musicName, d.volume)
            animator        = AnimLib.Animator.new()
            animator.rig    = figure
            animator.track = AnimLib.Track.fromfile(AssetGetPathFromFilename(d.anim:match("^[^@]+")))
            animator.looped = true
            animator.speed  = 1
        end

        m.Update = function(dt, figure)
            if animator then
                animator:Step(GetOverrideDanceMusicTime())
            end
        end

        m.Destroy = function(figure)
            animator = nil
        end

        return m
    end)
end

return modules
