-- Generated by KernelPacker
--  42 modules detected, 0 files kept same but concatenated
--
-- missing assets couldnt be downloaded or not found
-- Listed :
--   "Goodboy.mp3" needed by module "Big Hand Pat"
--   "Surfboard.anim" needed by module "SurfBoard"
--   "Surfboard.mp3" needed by module "SurfBoard"
--   "Goodboy.mp3" needed by module "Big Hand Rub"

local modules = {}

local dances = {
    -- from: You'reMine.lua
    {
        name        = "You're Mine",
        desc        = "Hi I'm baldy nice to meet ya! Fuck me in the ass and call me Patricia!, Uploaded by TrulyAReal",
        anim        = "You'reMine.anim@MARKET/MARKET_TrulyAReal/assets/oNWOu0Up_You'reMine.anim",
        song        = "You'reMine.mp3@MARKET/MARKET_TrulyAReal/assets/R95vjAWc_You'reMine.mp3",
        songId      = "You'reMine.mp3",
        musicName   = "You'reMine",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Don't eat ass in the config",
    },
    -- from: BigHandWave.lua
    {
        name        = "Big Hand Wave",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "BigHandWave.anim@MARKET/MARKET_TrulyAReal/assets/MhOC3PCL_BigHandWave.anim",
        song        = "BigHandWave.mp3@MARKET/MARKET_TrulyAReal/assets/8zV1k39w_BigHandWave.mp3",
        songId      = "BigHandWave.mp3",
        musicName   = "BigHandWave",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: Tantrum.lua
    {
        name        = "Tantrum",
        desc        = "WAAA WAA WAA. Uploaded by TrulyAReal",
        anim        = "Tantrum.anim@MARKET/MARKET_TrulyAReal/assets/HVa1KSfr_Tantrum.anim",
        song        = "Tantrum.mp3@MARKET/MARKET_TrulyAReal/assets/R8KYxu09_Tantrum.mp3",
        songId      = "Tantrum.mp3",
        musicName   = "Tantrum",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: BigHandPat.lua
    {
        name        = "Big Hand Pat",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "BigHandPat.anim@MARKET/MARKET_TrulyAReal/assets/BFBti12g_BigHandPat.anim",
        song        = "Goodboy.mp3",
        songId      = "Goodboy.mp3",
        musicName   = "Goodboy",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: SpiderDance.lua
    {
        name        = "Spider Dance",
        desc        = "Support Spider cause! Uploaded by TrulyAReal",
        anim        = "Spiderdance.anim@MARKET/MARKET_TrulyAReal/assets/pN8zH7Ve_Spiderdance.anim",
        song        = "SpiderDance.mp3@MARKET/MARKET_TrulyAReal/assets/RU3rC8Gi_SpiderDance.mp3",
        songId      = "SpiderDance.mp3",
        musicName   = "SpiderDance",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: BigHandFlick.lua
    {
        name        = "Big Hand Flick",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "BigHandFlick.anim@MARKET/MARKET_TrulyAReal/assets/5f6szXpZ_BigHandFlick.anim",
        song        = "BigHandFlick.mp3@MARKET/MARKET_TrulyAReal/assets/qQiwFaDU_BigHandFlick.mp3",
        songId      = "BigHandFlick.mp3",
        musicName   = "BigHandFlick",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: Thinking.lua
    {
        name        = "Big Hand: Thinking🤔",
        desc        = "mmmm donuts🤤🤤🤤. Uploaded by TrulyAReal",
        anim        = "Thinking.anim@MARKET/MARKET_TrulyAReal/assets/Ozjjw5lb_Thinking.anim",
        song        = "Thinking.mp3@MARKET/MARKET_TrulyAReal/assets/PeqhbXp6_Thinking.mp3",
        songId      = "Thinking.mp3",
        musicName   = "Thinking",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: BiblicallyAccurate.lua
    {
        name        = "Biblically Accurate Emote",
        desc        = "4th Dimension Creature. Uploaded by TrulyAReal",
        anim        = "BiblicallyAccurate.anim@MARKET/MARKET_TrulyAReal/assets/0kmp7Bel_BiblicallyAccurate.anim",
        song        = "BiblicallyAccurate.mp3@MARKET/MARKET_TrulyAReal/assets/hkHKj8vV_BiblicallyAccurate.mp3",
        songId      = "BiblicallyAccurate.mp3",
        musicName   = "BiblicallyAccurate",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Cthulu the goat 🙏",
    },
    -- from: Baller.lua
    {
        name        = "B A L L E R",
        desc        = "STOP POSTING ABOUT B A L L E R, Uploaded by TrulyAReal",
        anim        = "Baller.anim@MARKET/MARKET_TrulyAReal/assets/xE4SxfTa_Baller.anim",
        song        = "Baller.mp3@MARKET/MARKET_TrulyAReal/assets/jaiiVvcL_Baller.mp3",
        songId      = "Baller.mp3",
        musicName   = "Baller",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Im tried of seeing it",
    },
    -- from: ThinkBro.lua
    {
        name        = "Big Hand: Think, Bro, THINK!",
        desc        = "THINK, MARK, THINK.. Uploaded by TrulyAReal",
        anim        = "ThinkBro.anim@MARKET/MARKET_TrulyAReal/assets/FoYAP1JU_ThinkBro.anim",
        song        = "ThinkBro.mp3@MARKET/MARKET_TrulyAReal/assets/bfvkdQ5z_ThinkBro.mp3",
        songId      = "ThinkBro.mp3",
        musicName   = "ThinkBro",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: BigHandYap.lua
    {
        name        = "Big Hand Yap",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "BigHandYap.anim@MARKET/MARKET_TrulyAReal/assets/iXhG2YGa_BigHandYap.anim",
        song        = "BigHandYap.mp3@MARKET/MARKET_TrulyAReal/assets/WMgF6jgz_BigHandYap.mp3",
        songId      = "BigHandYap.mp3",
        musicName   = "BigHandYap",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: Boppin.lua
    {
        name        = "Boppin",
        desc        = "Hold on he hit every beat, Uploaded by TrulyAReal",
        anim        = "Boppin.anim@MARKET/MARKET_TrulyAReal/assets/x3YdUvXT_Boppin.anim",
        song        = "Boppin.mp3@MARKET/MARKET_TrulyAReal/assets/yi4AWXZ5_Boppin.mp3",
        songId      = "Boppin.mp3",
        musicName   = "Boppin",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
    -- from: BigHandYes.lua
    {
        name        = "Big Hand Yes",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "BigHandYes.anim@MARKET/MARKET_TrulyAReal/assets/J4zzQ3zD_BigHandYes.anim",
        song        = "BigHandYes.mp3@MARKET/MARKET_TrulyAReal/assets/GE6ANdXa_BigHandYes.mp3",
        songId      = "BigHandYes.mp3",
        musicName   = "BigHandYes",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: Leviathan.lua
    {
        name        = "Leviathan",
        desc        = "Thousand Yard Stare, Uploaded by TrulyAReal",
        anim        = "Leviathan.anim@MARKET/MARKET_TrulyAReal/assets/4JbO5Zxt_Leviathan.anim",
        song        = "Leviathan.mp3@MARKET/MARKET_TrulyAReal/assets/5pTSbGNK_Leviathan.mp3",
        songId      = "Leviathan.mp3",
        musicName   = "Leviathan",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Sabnautic 2 When?",
    },
    -- from: Mogged.lua
    {
        name        = "Big Hand: Mogged",
        desc        = "Rizz V3 Basically. Uploaded by TrulyAReal",
        anim        = "Mogged.anim@MARKET/MARKET_TrulyAReal/assets/yc9f5xGz_Mogged.anim",
        song        = "Mogged.mp3@MARKET/MARKET_TrulyAReal/assets/1CXEDJCx_Mogged.mp3",
        songId      = "Mogged.mp3",
        musicName   = "Mogged",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: BigHandDislike.lua
    {
        name        = "Big Hand Dislike",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "BigHandDislike.anim@MARKET/MARKET_TrulyAReal/assets/iEbbtzto_BigHandDislike.anim",
        song        = "BigHandDislike.mp3@MARKET/MARKET_TrulyAReal/assets/Ma4NHHn5_BigHandDislike.mp3",
        songId      = "BigHandDislike.mp3",
        musicName   = "BigHandDislike",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: Springlock.lua
    {
        name        = "Springlock Failure",
        desc        = "GET IT OFF. Uploaded by TrulyAReal",
        anim        = "SpringLock.anim@MARKET/MARKET_TrulyAReal/assets/HlaBIGYz_SpringLock.anim",
        song        = "SpringLock.mp3@MARKET/MARKET_TrulyAReal/assets/9K3CjvYr_SpringLock.mp3",
        songId      = "SpringLock.mp3",
        musicName   = "SpringLock",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: DrLivesey.lua
    {
        name        = "Dr Livesey Walk",
        desc        = "Rum is the same as death,Uploaded by TrulyAReal",
        anim        = "DrLivesey.anim@MARKET/MARKET_TrulyAReal/assets/XZrgmKtZ_DrLivesey.anim",
        song        = "DrLivesey.mp3@MARKET/MARKET_TrulyAReal/assets/KnAhTObo_DrLivesey.mp3",
        songId      = "DrLivesey.mp3",
        musicName   = "DrLivesey",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
    -- from: KickingFeet.lua
    {
        name        = "Cutely Kicking Feet",
        desc        = "What the fuck, is this. Uploaded by TrulyAReal",
        anim        = "KickingFeet.anim@MARKET/MARKET_TrulyAReal/assets/Z9NxGCUD_KickingFeet.anim",
        song        = "KickingFeet.mp3@MARKET/MARKET_TrulyAReal/assets/aL3j4RyS_KickingFeet.mp3",
        songId      = "KickingFeet.mp3",
        musicName   = "KickingFeet",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: SurfBoard.lua
    {
        name        = "SurfBoard",
        desc        = "Surfs up. Uploaded by TrulyAReal",
        anim        = "Surfboard.anim",
        song        = "Surfboard.mp3",
        songId      = "SurfBoard.mp3",
        musicName   = "SurfBoard",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = ":P",
    },
    -- from: TOOExcited.lua
    {
        name        = "Way Too Excited",
        desc        = "YIPYAPYAYAYIYIYIPYAYUA, Uploaded by TrulyAReal",
        anim        = "TOOExcited.anim@MARKET/MARKET_TrulyAReal/assets/FPWRpfEY_TOOExcited.anim",
        song        = "TOOExcited.mp3@MARKET/MARKET_TrulyAReal/assets/r538H4mw_TOOExcited.mp3",
        songId      = "TOOExcited.mp3",
        musicName   = "TOOExcited",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Gibberish Generator",
    },
    -- from: UnspokenRizz.lua
    {
        name        = "Unspoken Rizz",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "UnspokenRizz.anim@MARKET/MARKET_TrulyAReal/assets/4YRyqzZo_UnspokenRizz.anim",
        song        = "Rizz.mp3@MARKET/MARKET_TrulyAReal/assets/aQx4wTM1_Rizz.mp3",
        songId      = "Rizz.mp3",
        musicName   = "Rizz",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: Club Penguin.lua
    {
        name        = "Club Penguin",
        desc        = "Peak Gaming Uploaded by TrulyAReal",
        anim        = "Club Penguin.anim@MARKET/MARKET_TrulyAReal/assets/xzGKC9yT_Club Penguin.anim",
        song        = "Club Penguin.mp3@MARKET/MARKET_TrulyAReal/assets/2sPzk2Te_Club Penguin.mp3",
        songId      = "Club Penguin.mp3",
        musicName   = "Club Penguin",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
    -- from: BigHandComeHere.lua
    {
        name        = "Big Hand Come Here",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "BigHandComeHere.anim@MARKET/MARKET_TrulyAReal/assets/QyA4XpiX_BigHandComeHere.anim",
        song        = "BigHandComeHere.mp3@MARKET/MARKET_TrulyAReal/assets/4DRqksfH_BigHandComeHere.mp3",
        songId      = "BigHandComeHere.mp3",
        musicName   = "BigHandComeHere",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: SonicVictory.lua
    {
        name        = "Sonic Victory",
        desc        = "I'll bring it to court, but I don't think they'll take gotta go fast as a medical condition, Uploaded by TrulyAReal",
        anim        = "SonicVictory.anim@MARKET/MARKET_TrulyAReal/assets/PJihIEZy_SonicVictory.anim",
        song        = "SonicVictory.mp3@MARKET/MARKET_TrulyAReal/assets/UEX5uE9a_SonicVictory.mp3",
        songId      = "SonicVictory.mp3",
        musicName   = "SonicVictory",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Knuckles the chad",
    },
    -- from: BigHandRub.lua
    {
        name        = "Big Hand Rub",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "BigHandRub.anim@MARKET/MARKET_TrulyAReal/assets/2A2PN8AH_BigHandRub.anim",
        song        = "Goodboy.mp3",
        songId      = "Goodboy.mp3",
        musicName   = "Goodboy",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: Rizz.lua
    {
        name        = "Rizz",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "Rizz.anim@MARKET/MARKET_TrulyAReal/assets/zgVKy0fd_Rizz.anim",
        song        = "Rizz.mp3@MARKET/MARKET_TrulyAReal/assets/aQx4wTM1_Rizz.mp3",
        songId      = "Rizz.mp3",
        musicName   = "Rizz",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: Yippee.lua
    {
        name        = "Yippee",
        desc        = "My mother let me drink cola and play fortnite. Its cool! YIPPEE, Uploaded by TrulyAReal",
        anim        = "Boppin.anim@MARKET/MARKET_TrulyAReal/assets/x3YdUvXT_Boppin.anim",
        song        = "Boppin.mp3@MARKET/MARKET_TrulyAReal/assets/yi4AWXZ5_Boppin.mp3",
        songId      = "Yippee.mp3",
        musicName   = "Yippee",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "We Already YIPPEE no need to not YIPPEE.",
    },
    -- from: WOOHOO.lua
    {
        name        = "YES",
        desc        = "WOOHOO YES, Uploaded by TrulyAReal",
        anim        = "WOOHOO.anim@MARKET/MARKET_TrulyAReal/assets/yli4Q7tA_WOOHOO.anim",
        song        = "WOOHOO.mp3@MARKET/MARKET_TrulyAReal/assets/CgvULtVB_WOOHOO.mp3",
        songId      = "WOOHOO.mp3",
        musicName   = "WOOHOO",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
    -- from: DropKick.lua
    {
        name        = "Drop Kick",
        desc        = "Who's name is john cena? HOLY SHI-. Uploaded by TrulyAReal",
        anim        = "DropKick.anim@MARKET/MARKET_TrulyAReal/assets/RLhsKHY7_DropKick.anim",
        song        = "DropKick.mp3@MARKET/MARKET_TrulyAReal/assets/NJH9yNaW_DropKick.mp3",
        songId      = "DropKick.mp3",
        musicName   = "DropKick",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: Kaboom.lua
    {
        name        = "Kaboom",
        desc        = "KABOOOOM, Uploaded by TrulyAReal",
        anim        = "Kaboom.anim@MARKET/MARKET_TrulyAReal/assets/YjQCe91E_Kaboom.anim",
        song        = "Kaboom.mp3@MARKET/MARKET_TrulyAReal/assets/ekpNB8ei_Kaboom.mp3",
        songId      = "Kaboom.mp3",
        musicName   = "Kaboom",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
    -- from: JojoPose.lua
    {
        name        = "Jojo Pose",
        desc        = "Steal Ball Run is no more. Uploaded by TrulyAReal",
        anim        = "JojoPose.anim@MARKET/MARKET_TrulyAReal/assets/JlzhRnfs_JojoPose.anim",
        song        = "JojoPose.mp3@MARKET/MARKET_TrulyAReal/assets/WKqklq48_JojoPose.mp3",
        songId      = "JojoPose.mp3",
        musicName   = "JojoPose",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: BunnyEars.lua
    {
        name        = "Big Hand: Bunny Ears",
        desc        = "Shitty Bad Emote. Uploaded by TrulyAReal",
        anim        = "BunnyEars.anim@MARKET/MARKET_TrulyAReal/assets/xLAAIp4K_BunnyEars.anim",
        song        = "BunnyEars.mp3@MARKET/MARKET_TrulyAReal/assets/Ahn1fs8N_BunnyEars.mp3",
        songId      = "BunnyEars.mp3",
        musicName   = "BunnyEars",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: CyberCity.lua
    {
        name        = "Cyber City",
        desc        = "A Tyrannosaurus Rex A Quiet kid and a Fluffy boy, Uploaded by TrulyAReal",
        anim        = "CyberCity.anim@MARKET/MARKET_TrulyAReal/assets/BxSgIVxu_CyberCity.anim",
        song        = "CyberCity.mp3@MARKET/MARKET_TrulyAReal/assets/uNDF1vDp_CyberCity.mp3",
        songId      = "CyberCity.mp3",
        musicName   = "CyberCity",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Kris don't buy drugs from that shady business man INSTEAD buy them from me Toriel",
    },
    -- from: BigHandPoint.lua
    {
        name        = "Big Hand Point",
        desc        = "Sick Ass Emote. Uploaded by TrulyAReal",
        anim        = "BigHandPoint.anim@MARKET/MARKET_TrulyAReal/assets/42PDfHbD_BigHandPoint.anim",
        song        = "13.mp3@MARKET/MARKET_TrulyAReal/assets/NpvQFrr4_13.mp3",
        songId      = "13.mp3",
        musicName   = "13",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "Big Hand Series",
    },
    -- from: BodyDial.lua
    {
        name        = "BodyDial",
        desc        = "Ah yes, the true portable phone. Uploaded by TrulyAReal",
        anim        = "BodyDial.anim@MARKET/MARKET_TrulyAReal/assets/MabkTyCd_BodyDial.anim",
        song        = "BodyDial.mp3@MARKET/MARKET_TrulyAReal/assets/93J0nadh_BodyDial.mp3",
        songId      = "BodyDial.mp3",
        musicName   = "BodyDial",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "took so fucking long",
    },
    -- from: ThraggAura.lua
    {
        name        = "Thragg Aura",
        desc        = "The goat of aura, Uploaded by TrulyAReal",
        anim        = "ThraggAura.anim@MARKET/MARKET_TrulyAReal/assets/0QI6oKzZ_ThraggAura.anim",
        song        = "ThraggAura.mp3@MARKET/MARKET_TrulyAReal/assets/XSFs7XmH_ThraggAura.mp3",
        songId      = "ThraggAura.mp3",
        musicName   = "ThraggAura",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
    -- from: EffortlessAura.lua
    {
        name        = "Effortless Aura",
        desc        = "Ts so brainrotted,  Uploaded by TrulyAReal",
        anim        = "EffortlessAura.anim@MARKET/MARKET_TrulyAReal/assets/XlPEHiIG_EffortlessAura.anim",
        song        = "EffortlessAura.mp3@MARKET/MARKET_TrulyAReal/assets/9fvmfys4_EffortlessAura.mp3",
        songId      = "EffortlessAura.mp3",
        musicName   = "EffortlessAura",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
    -- from: FoggyMountain.lua
    {
        name        = "Foggy Mountain",
        desc        = "Mid ass dance, Uploaded by TrulyAReal",
        anim        = "FoggyMountain.anim@MARKET/MARKET_TrulyAReal/assets/f0Yrylgl_FoggyMountain.anim",
        song        = "FoggyMountain.mp3@MARKET/MARKET_TrulyAReal/assets/4LDZwOxh_FoggyMountain.mp3",
        songId      = "FoggyMountain.mp3",
        musicName   = "FoggyMountain",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "random emote",
    },
    -- from: Helicopter.lua
    {
        name        = "Helicopter",
        desc        = "HELICOPTER, HELICOPTER! Uploaded by TrulyAReal",
        anim        = "Helicopter.anim@MARKET/MARKET_TrulyAReal/assets/ZcMvikZg_Helicopter.anim",
        song        = "Helicopter.mp3@MARKET/MARKET_TrulyAReal/assets/nksqHIkM_Helicopter.mp3",
        songId      = "Helicopter.mp3",
        musicName   = "Helicopter",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
    -- from: Tank.lua
    {
        name        = "Tank",
        desc        = "Should have used Cola,Vodka,Whisky for the song -TrulyAReal",
        anim        = "Tank.anim@MARKET/MARKET_TrulyAReal/assets/z83Vk77c_Tank.anim",
        song        = "Tank.mp3@MARKET/MARKET_TrulyAReal/assets/GAZ3cma0_Tank.mp3",
        songId      = "Tank.mp3",
        musicName   = "Tank",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
    -- from: StartDiggin.lua
    {
        name        = "Start Diggin' Twin!",
        desc        = "What da hellll, aw hell no. Uploaded by TrulyAReal",
        anim        = "StartDiggin.anim@MARKET/MARKET_TrulyAReal/assets/nMlvU8B7_StartDiggin.anim",
        song        = "StartDiggin.mp3@MARKET/MARKET_TrulyAReal/assets/hSoOqwqN_StartDiggin.mp3",
        songId      = "StartDiggin.mp3",
        musicName   = "StartDiggin",
        volume      = 0.8,
        rangeLo     = 0,
        rangeHi     = 45.5,
        configText  = "No settings.",
    },
}

for i = 1, #dances do
    local d = dances[i]
    table.insert(modules, function()
        local m = {}
        local animator = nil
        local start = 0

        m.ModuleType  = "DANCE"
        m.Name        = d.name
        m.Description = d.desc
        m.Assets      = {d.anim, d.song}

        m.Config = function(parent)
            Util_CreateText(parent, d.configText, 14, Enum.TextXAlignment.Center)
        end

        m.SaveConfig = function() return {} end
        m.LoadConfig = function(save) end

        m.Init = function(figure)
            SetOverrideDanceMusic(AssetGetContentId(d.songId), d.musicName, d.volume, NumberRange.new(d.rangeLo, d.rangeHi))

            start           = os.clock()
            animator        = AnimLib.Animator.new()
            animator.rig    = figure
            animator.track  = AnimLib.Track.fromfile(AssetGetPathFromFilename(d.anim))
            animator.looped = true
            animator.speed  = 1
        end

        m.Update = function(dt, figure)
            animator:Step(os.clock() - start)
        end

        m.Destroy = function(figure)
            animator = nil
        end

        return m
    end)
end

return modules
