-- Generated by KernelPacker
--  0 dance module(s) folded, 1 other module file(s)
--  Total asset size (anim + music): 4.43 MB

local modules = {}


-- cm

-- from: John reanimate.lua
do
local ok, result = pcall(function()
local modules = {}
table.insert(modules, function()
	local m = {}
	m.ModuleType = "MOVESET"
	m.Name = "john doe"
	m.Description = "the corruption that once took HIM.\n\nGAHHHH GRAHHH1!1!1!!1! (made by Berry, duh)..\n\nprobably for people who uses a John doe avatar and waiting for Uhhhhhh reanimate to put a John doe moveset."
	m.InternalName = "John_doe"
	m.Assets = {
		"DOEIDLE.anim@MARKET/MARKET_UpdatedJohndoe/assets/QIsmiErC_DOEIDLE.anim",
		"DOEWALK.anim@MARKET/MARKET_UpdatedJohndoe/assets/2RmZtAgl_DOEWALK.anim",
		"DOERUN.anim@MARKET/MARKET_UpdatedJohndoe/assets/5iKhZGPv_DOERUN.anim",
		"DOEM1.anim@MARKET/MARKET_UpdatedJohndoe/assets/XLzu2AbI_DOEM1.anim",
		"DOECORRUPT.anim@MARKET/MARKET_UpdatedJohndoe/assets/9rUfT9IL_DOECORRUPT.anim",
		"DOEKILL.anim@MARKET/MARKET_UpdatedJohndoe/assets/RUA8iEhd_DOEKILL.anim",
		"DOEINTRO.anim@MARKET/MARKET_UpdatedJohndoe/assets/MRjBlYX9_DOEINTRO.anim",
		"DOEJANEKILL.anim@MARKET/MARKET_UpdatedJohndoe/assets/xkrpJtXG_DOEJANEKILL.anim",
		"DOEJANEVICTIM.anim@MARKET/MARKET_UpdatedJohndoe/assets/IFLsCj1h_DOEJANEVICTIM.anim",
		"DOESTUNSTART.anim@MARKET/MARKET_UpdatedJohndoe/assets/1qe9Ulbv_DOESTUNSTART.anim",
		"DOESTUNLOOP.anim@MARKET/MARKET_UpdatedJohndoe/assets/1iUa4H9r_DOESTUNLOOP.anim",
		"DOESTUNEND.anim@MARKET/MARKET_UpdatedJohndoe/assets/QrGpIrTe_DOESTUNEND.anim",
		"DOESTUNCANCEL.anim@MARKET/MARKET_UpdatedJohndoe/assets/UuumCmut_DOESTUNCANCEL.anim",
		"DOEKILLVICTIM.anim@MARKET/MARKET_UpdatedJohndoe/assets/CyrkHqFw_DOEKILLVICTIM.anim",
      "DOEFOOTPRINT.anim@MARKET/MARKET_UpdatedJohndoe/assets/yqxqVwHB_DOEFOOTPRINT.anim",
		"DOEOUTRO.anim@MARKET/MARKET_UpdatedJohndoe/assets/LbOjsxmc_DOEOUTRO.anim",
		"DOEM1.mp3@MARKET/MARKET_UpdatedJohndoe/assets/QGmiSGzi_DOEM1.mp3",
		"DOECORRUPT.mp3@MARKET/MARKET_UpdatedJohndoe/assets/2OtA4YWq_DOECORRUPT.mp3",
      "DOEFOOTPRINT.mp3@MARKET/MARKET_UpdatedJohndoe/assets/chGYEbnd_DOEFOOTPRINT.mp3",
		"DOEKILL.mp3@MARKET/MARKET_UpdatedJohndoe/assets/c0nsnxu1_DOEKILL.mp3",
		"DOEINTRO.mp3@MARKET/MARKET_UpdatedJohndoe/assets/3F9MbxS2_DOEINTRO.mp3",
		"DOEJANEKILL.mp3@MARKET/MARKET_UpdatedJohndoe/assets/bbq4Yak0_DOEJANEKILL.mp3",
		"DOESTUNSTART.mp3@MARKET/MARKET_UpdatedJohndoe/assets/iPOMQ0PR_DOESTUNSTART.mp3",
		"DOESTUNCANCEL.mp3@MARKET/MARKET_UpdatedJohndoe/assets/Q093nsVf_DOESTUNCANCEL.mp3",
		"DOEERROR.mp3@MARKET/MARKET_UpdatedJohndoe/assets/XSPWfxOh_DOEERROR.mp3",
		"DOEOUTRO.mp3@MARKET/MARKET_UpdatedJohndoe/assets/z49l3jbb_DOEOUTRO.mp3",
		"CorruptionthattookHim.mp3@MARKET/MARKET_UpdatedJohndoe/assets/WOLBEoik_CorruptionthattookHim.mp3",
		"DOEIDLEVOICE.mp3@MARKET/MARKET_UpdatedJohndoe/assets/dhbozUtk_DOEIDLEVOICE.mp3",
	}
	m.Config = function(parent) end

	local Players      = game:GetService("Players")
	local Debris       = game:GetService("Debris")
	local UIS          = game:GetService("UserInputService")
	local RunService   = game:GetService("RunService")
	local Player       = Players.LocalPlayer

	local animator        = nil
	local tracks          = {}
	local currentTrack    = nil
	local animationTime   = 0
	local lastState       = "none"
	local usingSkill      = false
	local isSprinting     = false
	local flingActive     = false
	local touchConns      = {}
	local figureRef       = nil
	local activeVictims   = {}
	local idleVoiceActive = false
	local isM1Active      = false  
	local m1AnimTime      = 0      
	local lowerAnimator   = nil    

	
	local LOWER_BODY_JOINTS = {
		["Left Hip"]   = true,
		["Right Hip"]  = true,
		["LeftUpperLeg"]  = true, ["LeftLowerLeg"]  = true, ["LeftFoot"]  = true,
		["RightUpperLeg"] = true, ["RightLowerLeg"] = true, ["RightFoot"] = true,
	}

	
	
	local janeAnchorConn     = nil
	local errorSlowActive    = false
	local errorSlowSpeed     = 2
	local unstoppableActive  = false   

	local function playSound(id, parent)
		local s = Instance.new("Sound")
		s.SoundId = AssetGetContentId(id)
		s.Volume  = 1.5
		s.Parent  = parent
		s:Play()
		Debris:AddItem(s, 10)
	end

	local function loadAnim(fig, file, looped)
		local a      = AnimLib.Animator.new()
		a.rig        = fig
		a.track      = AnimLib.Track.fromfile(AssetGetPathFromFilename(file))
		a.looped     = looped or false
		a.speed      = 1
		a.weight     = 0
		return a
	end

	local function anchorPlayer(figure, on)
		local root = figure:FindFirstChild("HumanoidRootPart")
		if root then root.Anchored = on end
	end

	
	
	local function startJaneAnchor(dummy)
		if janeAnchorConn then
			janeAnchorConn:Disconnect()
			janeAnchorConn = nil
		end
		if not dummy then return end
		local dRoot = dummy:FindFirstChild("HumanoidRootPart") or dummy:FindFirstChild("Torso")
		if not dRoot then return end
		dummy.PrimaryPart = dRoot
		janeAnchorConn = RunService.Heartbeat:Connect(function()
			if not dummy or not dummy.Parent then
				if janeAnchorConn then
					janeAnchorConn:Disconnect()
					janeAnchorConn = nil
				end
				return
			end
			local myRoot = figureRef and (
				figureRef:FindFirstChild("HumanoidRootPart") or
				figureRef:FindFirstChild("Torso")
			)
			if myRoot then
				dummy:PivotTo(myRoot.CFrame * CFrame.new(0, -9, 0))
			end
		end)
	end

	local function stopJaneAnchor()
		if janeAnchorConn then
			janeAnchorConn:Disconnect()
			janeAnchorConn = nil
		end
	end

	local function setupFlingTouched(figure)
		local function hookPart(part)
			local conn = part.Touched:Connect(function(hit)
				if not hit or not hit.Parent then return end
				local target = hit.Parent
				if target:IsA("Accessory") then target = target.Parent end
				if target == figure then return end
				if not target:FindFirstChildOfClass("Humanoid") then return end
				if flingActive then
					ReanimateFling(target)
				end
			end)
			table.insert(touchConns, conn)
		end
		for _, part in ipairs(figure:GetDescendants()) do
			if part:IsA("BasePart") then hookPart(part) end
		end
		table.insert(touchConns, figure.DescendantAdded:Connect(function(part)
			if part:IsA("BasePart") then hookPart(part) end
		end))
	end

	
	local JANE_KILL_TARGET = "idkmanel8"

	
	
	
	
	
	
	
	
	local function spawnVictimNPC(victimName, targetPlayer, offsetCFrame, animName, duration)
		if not figureRef then return end
		local dummy

		
		if targetPlayer and targetPlayer.Character then
			pcall(function()
				targetPlayer.Character.Archivable = true
				dummy = targetPlayer.Character:Clone()
				targetPlayer.Character.Archivable = false
			end)
		end

		
		if not dummy then
			pcall(function()
				figureRef.Archivable = true
				dummy = figureRef:Clone()
				figureRef.Archivable = false
			end)
		end

		
		if not dummy then
			pcall(function()
				dummy = Players:CreateHumanoidModelFromDescription(
					Instance.new("HumanoidDescription"),
					Enum.HumanoidRigType.R6
				)
			end)
		end
		if not dummy then return nil end

		dummy.Name   = victimName
		dummy.Parent = workspace

		
		
		for _, v in ipairs(dummy:GetDescendants()) do
			if v:IsA("Script") or v:IsA("LocalScript") or v:IsA("Sound")
			or v:IsA("ScreenGui") or v:IsA("BillboardGui") or v:IsA("SurfaceGui") then
				v:Destroy()
			elseif v:IsA("BasePart") then
				v.Massless   = true
				v.CanCollide = false
				v.CanTouch   = false
				v.CanQuery   = false
				
				v.Anchored   = (v.Name == "HumanoidRootPart")
			end
		end

		local myRoot = figureRef:FindFirstChild("HumanoidRootPart")
			or figureRef:FindFirstChild("Torso")
		local dRoot  = dummy:FindFirstChild("HumanoidRootPart")
			or dummy:FindFirstChild("Torso")
		if myRoot and dRoot then
			dummy.PrimaryPart = dRoot
			dummy:PivotTo(myRoot.CFrame * offsetCFrame)
		end

		local ok, dAnim = pcall(function()
			return loadAnim(dummy, animName, false)
		end)
		if ok and dAnim then
			dAnim.weight = 1
			table.insert(activeVictims, {
				anim  = dAnim,
				dummy = dummy,
				start = os.clock(),   
			})
		end
		Debris:AddItem(dummy, duration + 0.5)
		return dummy
	end

	
	local function getRandomPlayer()
		local valid = {}
		for _, p in ipairs(Players:GetPlayers()) do
			if p ~= Player and p.Character and p.Character:FindFirstChild("HumanoidRootPart") then
				table.insert(valid, p)
			end
		end
		return #valid > 0 and valid[math.random(1, #valid)] or nil
	end

	local function showTempESP(duration)
		local highlights = {}

		for _, p in ipairs(Players:GetPlayers()) do
			if p ~= Player and p.Character then
				local hl = Instance.new("Highlight")
				hl.Adornee          = p.Character
				hl.FillColor        = Color3.fromRGB(180, 0, 0)
				hl.FillTransparency = 0.4
				hl.OutlineColor     = Color3.fromRGB(255, 60, 60)
				hl.OutlineTransparency = 0
				hl.DepthMode        = Enum.HighlightDepthMode.AlwaysOnTop
				hl.Enabled          = true
				hl.Parent           = p.Character
				table.insert(highlights, hl)
			end
		end

		task.delay(duration, function()
			for _, hl in ipairs(highlights) do
				if hl and hl.Parent then
					hl:Destroy()
				end
			end
		end)
	end

	m.Init = function(figure)
		figureRef = figure
		local hum  = figure:FindFirstChildOfClass("Humanoid")
		local root = figure:FindFirstChild("HumanoidRootPart")
		if not hum or not root then return end

		animator         = AnimLib.Animator.new()
		animator.rig     = figure
		animator.looped  = true

		tracks.idle          = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOEIDLE.anim"))
		tracks.walk          = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOEWALK.anim"))
		tracks.run           = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOERUN.anim"))
		tracks.m1            = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOEM1.anim"))
		tracks.corrupt       = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOECORRUPT.anim"))
		tracks.kill          = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOEKILL.anim"))
		tracks.intro         = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOEINTRO.anim"))
		tracks.jane          = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOEJANEKILL.anim"))
		tracks.stunnedStart  = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOESTUNSTART.anim"))
		tracks.stunnedLoop   = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOESTUNLOOP.anim"))
		tracks.stunnedEnd    = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOESTUNEND.anim"))
		tracks.stunnedCancel = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOESTUNCANCEL.anim"))
      tracks.footprint = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOEFOOTPRINT.anim"))
		tracks.outro         = AnimLib.Track.fromfile(AssetGetPathFromFilename("DOEOUTRO.anim"))

		currentTrack   = tracks.idle
		animator.track = currentTrack

		
		
		lowerAnimator        = AnimLib.Animator.new()
		lowerAnimator.rig    = figure
		lowerAnimator.looped = true
		lowerAnimator.track  = tracks.idle
		lowerAnimator.weight = 1

		SetOverrideMovesetMusic(AssetGetContentId("CorruptionthattookHim.mp3"), "JOHN DOE IF HE WAS A DIFFERENT AVATAR", 1)
		setupFlingTouched(figure)

		idleVoiceActive = true
		task.spawn(function()
			while idleVoiceActive do
				local delay = math.random(15, 35)
				task.wait(delay)
				if not idleVoiceActive then break end
				if not usingSkill then
					playSound("DOEIDLEVOICE.mp3", root)
				end
			end
		end)

		ContextActions:BindAction("doe_m1", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill or isM1Active then return end
			
			
			isM1Active   = true
			flingActive  = true
			m1AnimTime   = 0
			playSound("DOEM1.mp3", root)
			
			currentTrack   = tracks.m1
			animator.track = currentTrack
			task.spawn(function()
				task.wait(0.9333)
				flingActive  = false
				isM1Active   = false
				lastState    = "none"
				
			end)
		end, true, Enum.UserInputType.MouseButton1)

		ContextActions:BindAction("doe_corrupt", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill         = true
			flingActive        = true
			hum.WalkSpeed      = 0
			hum.JumpPower      = 0
			playSound("DOECORRUPT.mp3", root)
			currentTrack       = tracks.corrupt
			animator.track     = currentTrack
			animationTime      = 0
			task.wait(3.20)
			flingActive        = false
			usingSkill         = false
			hum.WalkSpeed      = 8
			hum.JumpPower      = 50
			lastState          = "none"
		end, true, Enum.KeyCode.E)

		ContextActions:BindAction("doe_kill", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			anchorPlayer(figure, true)
			playSound("DOEKILL.mp3", root)
			currentTrack   = tracks.kill
			animator.track = currentTrack
			animationTime  = 0
			
			task.spawn(function()
				spawnVictimNPC(
					"Donut",
					getRandomPlayer(),
					CFrame.new(0, 0, -4) * CFrame.Angles(0, math.pi, 0),
					"DOEKILLVICTIM.anim",
					2.42
				)
			end)
			task.wait(2.7833)
			anchorPlayer(figure, false)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.Z)

		ContextActions:BindAction("doe_intro", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("DOEINTRO.mp3", root)
			currentTrack   = tracks.intro
			animator.track = currentTrack
			animationTime  = 0
			task.wait(5.00)
			usingSkill     = false
			hum.WalkSpeed  = 8
			hum.JumpPower  = 50
			lastState      = "none"
		end, true, Enum.KeyCode.One)

		ContextActions:BindAction("doe_jane_kill", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill    = true
			hum.WalkSpeed = 0
			hum.JumpPower = 0
			anchorPlayer(figure, true)

			playSound("DOEM1.mp3", root)
			isM1Active   = true
			m1AnimTime   = 0
			currentTrack   = tracks.m1
			animator.track = currentTrack

			local janeDummy = nil
			task.spawn(function()
				local d

				for _, p in ipairs(Players:GetPlayers()) do
					if p.Name == JANE_KILL_TARGET and p.Character then
						pcall(function()
							p.Character.Archivable = true
							d = p.Character:Clone()
							p.Character.Archivable = false
						end)
						break
					end
				end

				if not d then
					pcall(function()
						local uid  = Players:GetUserIdFromNameAsync(JANE_KILL_TARGET)
						local desc = Players:GetHumanoidDescriptionFromUserId(uid)
						d = Players:CreateHumanoidModelFromDescription(desc, Enum.HumanoidRigType.R6)
					end)
				end

				if not d then
					pcall(function()
						local desc = Players:GetHumanoidDescriptionFromUserId(Player.UserId)
						d = Players:CreateHumanoidModelFromDescription(desc, Enum.HumanoidRigType.R6)
					end)
				end

				if not d then
					pcall(function()
						d = Players:CreateHumanoidModelFromDescription(
							Instance.new("HumanoidDescription"), Enum.HumanoidRigType.R6)
					end)
				end
				janeDummy = d
			end)

			task.wait(0.9333)
			isM1Active = false

			playSound("DOEJANEKILL.mp3", root)
			currentTrack   = tracks.jane
			animator.track = currentTrack
			animationTime  = 0

			if janeDummy then
				janeDummy.Name   = "JaneVictim"
				janeDummy.Parent = workspace

				for _, v in ipairs(janeDummy:GetDescendants()) do
					if v:IsA("Script") or v:IsA("LocalScript") or v:IsA("Sound")
					or v:IsA("ScreenGui") or v:IsA("BillboardGui") or v:IsA("SurfaceGui") then
						v:Destroy()
					elseif v:IsA("BasePart") then
						v.Massless   = true
						v.CanCollide = false
						v.CanTouch   = false
						v.CanQuery   = false
						v.Anchored   = (v.Name == "HumanoidRootPart")
					end
				end

				local myRoot = figureRef and (figureRef:FindFirstChild("HumanoidRootPart") or figureRef:FindFirstChild("Torso"))
				local dRoot  = janeDummy:FindFirstChild("HumanoidRootPart") or janeDummy:FindFirstChild("Torso")
				if myRoot and dRoot then
					janeDummy.PrimaryPart = dRoot
					janeDummy:PivotTo(myRoot.CFrame * CFrame.new(0, 0, 0))
				end

				local ok, dAnim = pcall(function()
					return loadAnim(janeDummy, "DOEJANEVICTIM.anim", false)
				end)
				if ok and dAnim then
					dAnim.weight = 1
					table.insert(activeVictims, { anim = dAnim, dummy = janeDummy, start = os.clock() })
				end
				Debris:AddItem(janeDummy, 4.65 + 0.5)
			end

			task.wait(4.65)
			anchorPlayer(figure, false)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.Two)

		ContextActions:BindAction("doe_stun", function(_, state)
			if usingSkill then return end

			if state == Enum.UserInputState.Begin then
				
				if unstoppableActive then
					usingSkill    = true
					hum.WalkSpeed = 0
					hum.JumpPower = 0
					currentTrack   = tracks.stunnedCancel
					animator.track = currentTrack
					animationTime  = 0
					
					task.delay(1.999, function()
						if figureRef then
							local r = figureRef:FindFirstChild("HumanoidRootPart")
							if r then playSound("DOESTUNCANCEL.mp3", r) end
						end
					end)
					task.wait(3.25)   
					usingSkill    = false
					hum.WalkSpeed = 8
					hum.JumpPower = 50
					lastState     = "none"
					return
				end

				
				usingSkill    = true
				hum.WalkSpeed = 0
				hum.JumpPower = 0

				currentTrack   = tracks.stunnedStart
				animator.track = currentTrack
				animationTime  = 0
				playSound("DOESTUNSTART.mp3", root)
				task.wait(0.7333)

				currentTrack   = tracks.stunnedLoop
				animator.track = currentTrack
				animationTime  = 0
				task.wait(1)

				currentTrack   = tracks.stunnedEnd
				animator.track = currentTrack
				animationTime  = 0
				task.wait(1.00)

				usingSkill    = false
				hum.WalkSpeed = 8
				hum.JumpPower = 50
				lastState     = "none"
			end
		end, true, Enum.KeyCode.Q)

		ContextActions:BindAction("doe_error", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			local prevWalk  = hum.WalkSpeed
			local prevJump  = hum.JumpPower
			playSound("DOEERROR.mp3", root)
			errorSlowSpeed  = math.max(prevWalk * 0.30, 2)
			errorSlowActive = true
			isSprinting     = false
			hum.WalkSpeed   = errorSlowSpeed
			hum.JumpPower   = 0
			showTempESP(6)

			
			unstoppableActive = true
			ContextActions:SetTitle("doe_stun", "Unstoppable")

			task.wait(2)

			
			unstoppableActive = false
			ContextActions:SetTitle("doe_stun", "Stun")

			errorSlowActive = false
			if not usingSkill then
				hum.WalkSpeed = prevWalk
				hum.JumpPower = prevJump
			end
		end, true, Enum.KeyCode.R)

      ContextActions:BindAction("doe_footprint", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("DOEFOOTPRINT.mp3", root)
			currentTrack   = tracks.footprint
			animator.track = currentTrack
			animationTime  = 0
			task.wait(3.067)
			usingSkill     = false
			hum.WalkSpeed  = 8
			hum.JumpPower  = 50
			lastState      = "none"
		end, true, Enum.KeyCode.Four)

		ContextActions:BindAction("doe_outro", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("DOEOUTRO.mp3", root)
			currentTrack   = tracks.outro
			animator.track = currentTrack
			animationTime  = 0
			task.wait(6.6667)
			usingSkill     = false
			hum.WalkSpeed  = 8
			hum.JumpPower  = 50
			lastState      = "none"
		end, true, Enum.KeyCode.Three)

		ContextActions:BindAction("doe_sprint", function(_, state)
			if state == Enum.UserInputState.Begin then
				isSprinting = not isSprinting
				ContextActions:SetTitle("doe_sprint", isSprinting and "Walk" or "Sprint")
			end
		end, true, Enum.KeyCode.LeftShift)

		ContextActions:SetTitle("doe_m1",        "M1")
		ContextActions:SetTitle("doe_corrupt",   "Corrupt")
		ContextActions:SetTitle("doe_kill",      "Kill")
		ContextActions:SetTitle("doe_intro",     "Intro")
		ContextActions:SetTitle("doe_jane_kill", "JaneKill")
		ContextActions:SetTitle("doe_stun",      "Stun")
		ContextActions:SetTitle("doe_error",     "Error")
      ContextActions:SetTitle("doe_footprint",      "Digital")
		ContextActions:SetTitle("doe_outro",     "Outro")
		ContextActions:SetTitle("doe_sprint",    "Sprint")

		ContextActions:SetPosition("doe_m1",        UDim2.new(1,-70,  1,-70))
		ContextActions:SetPosition("doe_corrupt",   UDim2.new(1,-140, 1,-70))
		ContextActions:SetPosition("doe_kill",      UDim2.new(1,-210, 1,-70))
		ContextActions:SetPosition("doe_footprint",    UDim2.new(1,-280, 1,-70))
      ContextActions:SetPosition("doe_sprint", UDim2.new(1, -350, 1, -70))
		ContextActions:SetPosition("doe_intro",     UDim2.new(1,-70,  1,-150))
		ContextActions:SetPosition("doe_jane_kill", UDim2.new(1,-140, 1,-150))
		ContextActions:SetPosition("doe_stun",      UDim2.new(1,-210, 1,-150))
		ContextActions:SetPosition("doe_error",     UDim2.new(1,-280, 1,-150))
		ContextActions:SetPosition("doe_outro",     UDim2.new(1,-350, 1,-150))
	end

	m.Update = function(dt, figure)
		if not animator then return end
		local hum = figure:FindFirstChildOfClass("Humanoid")
		if not hum then return end

		
		local now = os.clock()
		for i = #activeVictims, 1, -1 do
			local data = activeVictims[i]
			if data.dummy and data.dummy.Parent then
				data.anim:Step(now - data.start)
			else
				table.remove(activeVictims, i)
			end
		end

		
		if not usingSkill then
			local state = "idle"
			if hum.MoveDirection.Magnitude > 0.1 then
				state = isSprinting and "run" or "walk"
			end

			if lastState ~= state then
				animationTime = 0
				lastState     = state
			end

			local newTrack
			if state == "idle" then
				newTrack = tracks.idle
				hum.WalkSpeed = errorSlowActive and errorSlowSpeed or 8
			elseif state == "walk" then
				newTrack = tracks.walk
				hum.WalkSpeed = errorSlowActive and errorSlowSpeed or 8
			elseif state == "run" then
				newTrack = tracks.run
				hum.WalkSpeed = errorSlowActive and errorSlowSpeed or 27.5
			end

			
			if lowerAnimator and newTrack and lowerAnimator.track ~= newTrack then
				lowerAnimator.track  = newTrack
				lowerAnimator.looped = true
			end

			
			if not isM1Active then
				if currentTrack ~= newTrack then
					currentTrack   = newTrack
					animator.track = currentTrack
				end
			end
		end

		animationTime += dt

		if isM1Active then
			
			
			
			local LEG_JOINTS = {
				["Left Hip"]  = true,
				["Right Hip"] = true,
			}

			if lowerAnimator then
				
				lowerAnimator.looped = true
				lowerAnimator:Step(animationTime)

				
				local legSnapshot = {}
				for _, motor in ipairs(figure:GetDescendants()) do
					if motor:IsA("Motor6D") and LEG_JOINTS[motor.Name] then
						legSnapshot[motor] = motor.Transform
					end
				end

				
				m1AnimTime += dt
				animator.looped = false
				animator:Step(m1AnimTime)

				
				
				for motor, cf in pairs(legSnapshot) do
					motor.Transform = cf
				end
			else
				
				m1AnimTime += dt
				animator.looped = false
				animator:Step(m1AnimTime)
			end
		else
			
			if usingSkill then
				
				animator:Step(animationTime)
			else
				animator.looped = true
				animator:Step(animationTime)
			end
		end
	end

	m.Destroy = function()
		idleVoiceActive = false
		isSprinting     = false
		flingActive     = false
		usingSkill      = false
		errorSlowActive = false
		for _, conn in ipairs(touchConns) do conn:Disconnect() end
		table.clear(touchConns)
		for _, data in ipairs(activeVictims) do
			if data.dummy then data.dummy:Destroy() end
		end
		activeVictims = {}
		
		ContextActions:UnbindAction("doe_m1")
		ContextActions:UnbindAction("doe_corrupt")
		ContextActions:UnbindAction("doe_kill")
		ContextActions:UnbindAction("doe_intro")
		ContextActions:UnbindAction("doe_jane_kill")
		ContextActions:UnbindAction("doe_stun")
		ContextActions:UnbindAction("doe_error")
		ContextActions:UnbindAction("doe_footprint")
		ContextActions:UnbindAction("doe_outro")
		ContextActions:UnbindAction("doe_sprint")
		isM1Active    = false
		m1AnimTime    = 0
		lowerAnimator = nil
		animator      = nil
		tracks        = {}
		currentTrack  = nil
		figureRef     = nil
	end

	return m
end)
return modules

end)
if not ok then
    (warn or print)("[KernelPacker] failed to load John reanimate.lua: " .. tostring(result))
elseif type(result) == "table" and result ~= modules then
    for _, fn in ipairs(result) do table.insert(modules, fn) end
end
end

return modules
