-- Generated by KernelPacker
--  45 modules detected, 0 files kept same but concatenated

local modules = {}

local dances = {
    -- from: 73_days.lua
    {
        name        = "73 days",
        desc        = "Flower actually do that for 73 days?",
        anim        = "72Days.anim@MARKET/MARKET_Pipis/assets/x9EVwXLS_72Days.anim",
        song        = "73days.mp3@MARKET/MARKET_Pipis/assets/eohqnuWe_73days.mp3",
        musicName   = "73 days",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: all_nights_forevr.lua
    {
        name        = "All nights forevr",
        desc        = "Lovers and lovers...",
        anim        = "Allnights.anim@MARKET/MARKET_Pipis/assets/PPDzFKt8_Allnights.anim",
        song        = "Allnights.mp3@MARKET/MARKET_Pipis/assets/m86gTvre_Allnights.mp3",
        musicName   = "Allnights",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: bass_boosted_73_days.lua
    {
        name        = "Bass boosted 73 days",
        desc        = "(Bass boosted) Flower actually do that for 73 days?",
        anim        = "72Days.anim@MARKET/MARKET_Pipis/assets/x9EVwXLS_72Days.anim",
        song        = "bassboosted73days.mp3@MARKET/MARKET_Pipis/assets/uT0OFBuJ_bassboosted73days.mp3",
        musicName   = "bassboosted73days",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: cubibibibism.lua
    {
        name        = "Cubibibibism",
        desc        = "Ni! han!",
        anim        = "Cubibibibism.anim@MARKET/MARKET_Pipis/assets/NCZZUK3z_Cubibibibism.anim",
        song        = "Cubism.mp3@MARKET/MARKET_Pipis/assets/pvXU3gSf_Cubism.mp3",
        musicName   = "Cubism",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: everyone_get_in_the_car_we_are_leaving_this_town_now!.lua
    {
        name        = "Everyone get in the car we are leaving this town now!",
        desc        = "AHHHHHHHH WHAT THE , IMPOSSIBLE , THIS ISNT THE CAR NOOOOOOOOOOO NOOOOOOOOOO AHHHHHHHHHH HERMIT PURPLEEEEEE",
        anim        = "EVERYONEGETINTHECARWEARELEAVINGTHISTOWNNOWAHHHHHWHATTHEIMPOSSIBLETHISISNTTHECARNOOOOOOONOOOOOOOOOAHHHHHERMITPURPLE.anim@MARKET/MARKET_Pipis/assets/eOjV9BZs_EVERYONEGETINTHECARWEARELEAVINGTHISTOWNNOWAHHHHHWHATTHEIMPOSSIBLETHISISNTTHECARNOOOOOOONOOOOOOOOOAHHHHHERMITPURPLE.anim",
        song        = "CAR.mp3@MARKET/MARKET_Pipis/assets/iP4NfnkQ_CAR.mp3",
        musicName   = "CAR",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: helicopter.lua
    {
        name        = "Helicopter",
        desc        = "SPIN!",
        anim        = "heli.anim@MARKET/MARKET_Pipis/assets/NaFxKzUX_heli.anim",
        song        = "Heli.mp3@MARKET/MARKET_Pipis/assets/SFHLLnON_Heli.mp3",
        musicName   = "Heli",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: insane_insanity.lua
    {
        name        = "Insane insanity",
        desc        = "Insanity but you are in an asylum",
        anim        = "Doomed.anim@MARKET/MARKET_Pipis/assets/0YyXnodv_Doomed.anim",
        song        = "Doom.mp3@MARKET/MARKET_Pipis/assets/1694jjLU_Doom.mp3",
        musicName   = "Doom!",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: LOUDEST73DAYSDANCE.lua
    {
        name        = "Bass boosted 73 days",
        desc        = "(Bass boosted) Flower actually do that for 73 days?",
        anim        = "72Days.anim@MARKET/MARKET_Pipis/assets/x9EVwXLS_72Days.anim",
        song        = "bassboosted73days1.mp3@MARKET/MARKET_Pipis/assets/hghPDZCj_bassboosted73days1.mp3",
        musicName   = "bassboosted73days (1)",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: obsolete_meal.lua
    {
        name        = "Obsolete meal",
        desc        = "EAT. NOW.",
        anim        = "obsolete.anim@MARKET/MARKET_Pipis/assets/v7U4jxI7_obsolete.anim",
        song        = "Obsolete.mp3@MARKET/MARKET_Pipis/assets/l4SwgWR8_Obsolete.mp3",
        musicName   = "Obsolete",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: stuck_in_my_head.lua
    {
        name        = "Stuck in my head",
        desc        = "Music by supxr",
        anim        = "inhead.anim@MARKET/MARKET_Pipis/assets/QO0ZWzJ1_inhead.anim",
        song        = "inmyhead.mp3@MARKET/MARKET_Pipis/assets/GOF7D5hW_inmyhead.mp3",
        musicName   = "inmyhead",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: youremine!!.lua
    {
        name        = "You're MINE!",
        desc        = "This one...Yeah it doesn't have swearing",
        anim        = "Youreminebutsafe.anim@MARKET/MARKET_Pipis/assets/3ZRakn5t_Youreminebutsafe.anim",
        song        = "Youreminebutsafe.mp3@MARKET/MARKET_Pipis/assets/hNPoxvkd_Youreminebutsafe.mp3",
        musicName   = "Youreminebutsafe",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: that's_what_i_do!.lua
    {
        name        = "That's what I do!",
        desc        = "Axie song and baldi :face-drooling: :durr:",
        anim        = "Thatswhatido.anim@MARKET/MARKET_Pipis/assets/9a0TAzL4_Thatswhatido.anim",
        song        = "Thatswhatido.mp3@MARKET/MARKET_Pipis/assets/beZD94p0_Thatswhatido.mp3",
        musicName   = "Thatswhatido",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: spit_it_out.lua
    {
        name        = "SPIT IT OUT",
        desc        = "Got something to tell u..Got smth to say- got got got smth to tell u",
        anim        = "SpitItOutGirl.anim@MARKET/MARKET_Pipis/assets/U604jTmp_SpitItOutGirl.anim",
        song        = "SpitItOut.mp3@MARKET/MARKET_Pipis/assets/x1DUmLWk_SpitItOut.mp3",
        musicName   = "SpitItOut",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: bfdia_9_dance.lua
    {
        name        = "BFDIA 9 dance",
        desc        = "yeahhhh bfdia :DDDDDD",
        anim        = "Bfdiadance.anim@MARKET/MARKET_Pipis/assets/JM17aAZb_Bfdiadance.anim",
        song        = "HolyReferences.mp3@MARKET/MARKET_Pipis/assets/EPEEJSur_HolyReferences.mp3",
        musicName   = "HolyReferences",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: nervy.lua
    {
        name        = "Nervy",
        desc        = "Yeah i got nervy",
        anim        = "Nervy.anim@MARKET/MARKET_Pipis/assets/OjkW2wbp_Nervy.anim",
        song        = "Nerve.mp3@MARKET/MARKET_Pipis/assets/nC8ybSGK_Nerve.mp3",
        musicName   = "Nerve",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: overdrive.lua
    {
        name        = "OVERDRIVE",
        desc        = "TOUHOUUUUUUUUUUUUUUU...Idk if thats touhou related",
        anim        = "OVERDRIVEEE.anim@MARKET/MARKET_Pipis/assets/uxIuYxus_OVERDRIVEEE.anim",
        song        = "Overdriven.mp3@MARKET/MARKET_Pipis/assets/aWWIEfZh_Overdriven.mp3",
        musicName   = "Overdriven",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: dagemei.lua
    {
        name        = "Dagemei",
        desc        = "Dagemei yeah",
        anim        = "Dagemei.anim@MARKET/MARKET_Pipis/assets/o91gt2uF_Dagemei.anim",
        song        = "Dagemei.mp3@MARKET/MARKET_Pipis/assets/ss3taz1s_Dagemei.mp3",
        musicName   = "Dagemei",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Epoch.lua
    {
        name        = "Epoch meme , yeah thats it cuz yeah",
        desc        = "The living tombstone",
        anim        = "Epoch.anim@MARKET/MARKET_Pipis/assets/UzLIV51T_Epoch.anim",
        song        = "Epoch.mp3@MARKET/MARKET_Pipis/assets/PLrkQhp4_Epoch.mp3",
        musicName   = "Epoch",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: hypno_dance_(minion).lua
    {
        name        = "Hypno dance (Minion)",
        desc        = "The minion variant",
        anim        = "HypnoDanceMinion.anim@MARKET/MARKET_Pipis/assets/eg9w6t1o_HypnoDanceMinion.anim",
        song        = "Hypno.mp3@MARKET/MARKET_Pipis/assets/JSFJfwZZ_Hypno.mp3",
        musicName   = "Hypno",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: split!.lua
    {
        name        = "Split!",
        desc        = "Inspo : theo",
        anim        = "SplitDance.anim@MARKET/MARKET_Pipis/assets/UAyDtnm9_SplitDance.anim",
        song        = "Splitdance.mp3@MARKET/MARKET_Pipis/assets/YEhDJwvL_Splitdance.mp3",
        musicName   = "Splitdance",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Outdoor.lua
    {
        name        = "Outdoor",
        desc        = "Zachz Winner is peak ngl",
        anim        = "Outdoor.anim@MARKET/MARKET_Pipis/assets/Au7wNYKm_Outdoor.anim",
        song        = "Discloped.mp3@MARKET/MARKET_Pipis/assets/EdTJxJzh_Discloped.mp3",
        musicName   = "Discloped",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: sunday.lua
    {
        name        = "Sunday",
        desc        = "Sunday morning",
        anim        = "SundayMorning.anim@MARKET/MARKET_Pipis/assets/7XKraVoW_SundayMorning.anim",
        song        = "SundayMorning.mp3@MARKET/MARKET_Pipis/assets/ntpWNLvd_SundayMorning.mp3",
        musicName   = "SundayMorning",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: yarrarararar.lua
    {
        name        = "Yarrarararar",
        desc        = "Swinging my head to lined zombie boiiiiiiii",
        anim        = "Yarararara.anim@MARKET/MARKET_Pipis/assets/5tzHf7TK_Yarararara.anim",
        song        = "Yarara.mp3@MARKET/MARKET_Pipis/assets/aBjx8ID5_Yarara.mp3",
        musicName   = "Yarara",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: alter_ego.lua
    {
        name        = "Alter Ego",
        desc        = "100% death but cant die none so i aura :sunglasses:",
        anim        = "Egoist.anim@MARKET/MARKET_Pipis/assets/tbktUwg7_Egoist.anim",
        song        = "Alter.mp3@MARKET/MARKET_Pipis/assets/PtRs4dvY_Alter.mp3",
        musicName   = "Alter",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: opinions.lua
    {
        name        = "Opinions",
        desc        = "I swear i heard this animation meme WAY back then",
        anim        = "Opinions.anim@MARKET/MARKET_Pipis/assets/uSvzPc7N_Opinions.anim",
        song        = "Opinion.mp3@MARKET/MARKET_Pipis/assets/Dh9BNAx7_Opinion.mp3",
        musicName   = "Opinion",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: breakcore.lua
    {
        name        = "Breakcore",
        desc        = "This Emote and sound is WAY WOSRE than cry for me",
        anim        = "Breakcore.anim@MARKET/MARKET_Pipis/assets/BFom2uhF_Breakcore.anim",
        song        = "Breakcore.mp3@MARKET/MARKET_Pipis/assets/OZYG0hui_Breakcore.mp3",
        musicName   = "Breakcore",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: mailbox.lua
    {
        name        = "Mailbox",
        desc        = "Hah! i got ya -Sonic",
        anim        = "mailbox.anim@MARKET/MARKET_Pipis/assets/0NHDQDhj_mailbox.anim",
        song        = "Mailbox.mp3@MARKET/MARKET_Pipis/assets/IeLlE6g3_Mailbox.mp3",
        musicName   = "Mailbox",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: i_want_hair_like_yours.lua
    {
        name        = "I want hair like yours",
        desc        = "lowk giving glados vibe",
        anim        = "Likeyours.anim@MARKET/MARKET_Pipis/assets/BvdrNlXp_Likeyours.anim",
        song        = "Thing.mp3@MARKET/MARKET_Pipis/assets/8JWWQe4E_Thing.mp3",
        musicName   = "Thing",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: machine.lua
    {
        name        = "Machine",
        desc        = "I want To be a machinaaaaa",
        anim        = "Machine.anim@MARKET/MARKET_Pipis/assets/Sz6y2bHA_Machine.anim",
        song        = "Machine.mp3@MARKET/MARKET_Pipis/assets/fgKHaQAA_Machine.mp3",
        musicName   = "Machine",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: stop_nagging_me.lua
    {
        name        = "Stop nagging me",
        desc        = "Buchabuchaunese!",
        anim        = "Stopnaggingme.anim@MARKET/MARKET_Pipis/assets/9ERNNC2J_Stopnaggingme.anim",
        song        = "Nagging.mp3@MARKET/MARKET_Pipis/assets/bMvQRpkz_Nagging.mp3",
        musicName   = "Nagging",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: feeling_blueee.lua
    {
        name        = "Feeling Blueee",
        desc        = "",
        anim        = "Feelingblue.anim@MARKET/MARKET_Pipis/assets/MgVFhs3k_Feelingblue.anim",
        song        = "FeelingBlue.mp3@MARKET/MARKET_Pipis/assets/xBRxggXf_FeelingBlue.mp3",
        musicName   = "Feeling Blue",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: jevil.lua
    {
        name        = "Jevil",
        desc        = "That damn clown",
        anim        = "Jevil.anim@MARKET/MARKET_Pipis/assets/IDSl5JU7_Jevil.anim",
        song        = "Jevil.mp3@MARKET/MARKET_Pipis/assets/ldL2sTp2_Jevil.mp3",
        musicName   = "Jevil",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: kyu_kurarin.lua
    {
        name        = "Kyu kurarin",
        desc        = "Just like lag train and ltr , cloning",
        anim        = "Kyukurarin.anim@MARKET/MARKET_Pipis/assets/0ax5rpeO_Kyukurarin.anim",
        song        = "Kyukurarin.mp3@MARKET/MARKET_Pipis/assets/OT9UZX0x_Kyukurarin.mp3",
        musicName   = "Kyukurarin",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: imposter_syndrome.lua
    {
        name        = "Imposter Syndrome",
        desc        = "Yo i might not be myself",
        anim        = "ImposterSyndrome.anim@MARKET/MARKET_Pipis/assets/oGGjfqep_ImposterSyndrome.anim",
        song        = "ImposterSyndrome.mp3@MARKET/MARKET_Pipis/assets/tPfJzvCn_ImposterSyndrome.mp3",
        musicName   = "ImposterSyndrome",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: skeleton_orchestra_and_lilia.lua
    {
        name        = "Skeleton Orchestra And Lilia",
        desc        = "Who is Lilia?",
        anim        = "SkellyAndLilia.anim@MARKET/MARKET_Pipis/assets/tXgKakmP_SkellyAndLilia.anim",
        song        = "SkellyAndLilia.mp3@MARKET/MARKET_Pipis/assets/2kzR7ndj_SkellyAndLilia.mp3",
        musicName   = "SkellyAndLilia",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: chirumiru.lua
    {
        name        = "Chirumiru",
        desc        = "Chirumiru! Chirumiru Genki Chirumiru!",
        anim        = "ChirumiruCirno.anim@MARKET/MARKET_Pipis/assets/SJsV0xah_ChirumiruCirno.anim",
        song        = "ChirumiruCirno.mp3@MARKET/MARKET_Pipis/assets/agPzzfKS_ChirumiruCirno.mp3",
        musicName   = "ChirumiruCirno",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: bling-bang-born.lua
    {
        name        = "Bling-Bang-Born",
        desc        = "Ts was Relevant 3 years ago i think",
        anim        = "BlingBangBorn.anim@MARKET/MARKET_Pipis/assets/0RrZZBEP_BlingBangBorn.anim",
        song        = "BlingBangBorn.mp3@MARKET/MARKET_Pipis/assets/L1xGdAPV_BlingBangBorn.mp3",
        musicName   = "BlingBangBorn",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: clone_clone.lua
    {
        name        = "CLone Clone",
        desc        = "Hell yeah! Vocaloid",
        anim        = "CloneClone.anim@MARKET/MARKET_Pipis/assets/78GVtH1r_CloneClone.anim",
        song        = "CloneClone.mp3@MARKET/MARKET_Pipis/assets/LGRaJpQz_CloneClone.mp3",
        musicName   = "CloneClone",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: cicada.lua
    {
        name        = "Cicada",
        desc        = "Made on 6:22 06/14/2026 | by Pipis",
        anim        = "Cicada.anim@MARKET/MARKET_Pipis/assets/47mSzQxa_Cicada.anim",
        song        = "Cicada.mp3@MARKET/MARKET_Pipis/assets/GSFJgkue_Cicada.mp3",
        musicName   = "Cicada",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: da_ting_goes.lua
    {
        name        = "Da ting goes",
        desc        = "Da thing goes 😂",
        anim        = "Datinggoes.anim@MARKET/MARKET_Pipis/assets/g0ZzvQR4_Datinggoes.anim",
        song        = "Datinggoes.mp3@MARKET/MARKET_Pipis/assets/kw2TJJhE_Datinggoes.mp3",
        musicName   = "Datinggoes",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: lets_go_to_heaven!_(duo) (1).lua
    {
        name        = "Lets go to heaven! (DUO)",
        desc        = "The hand got leaded",
        anim        = "LetsgotoheavenDuo2.anim@MARKET/MARKET_Pipis/assets/Erk38H2C_LetsgotoheavenDuo2.anim",
        song        = "Letsgotoheaven.mp3@MARKET/MARKET_Pipis/assets/oxbuFtwM_Letsgotoheaven.mp3",
        musicName   = "Letsgotoheaven",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: lets_go_to_heaven!_(duo) (2).lua
    {
        name        = "Lets go to heaven! (DUO)",
        desc        = "The leading hand",
        anim        = "LetsgotoheavenDuo1.anim@MARKET/MARKET_Pipis/assets/hm9D0Qvb_LetsgotoheavenDuo1.anim",
        song        = "Letsgotoheaven.mp3@MARKET/MARKET_Pipis/assets/oxbuFtwM_Letsgotoheaven.mp3",
        musicName   = "Letsgotoheaven",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: kekkaorai.lua
    {
        name        = "Kekkaorai",
        desc        = "Hel yeh another mi dance",
        anim        = "Vigilanties.anim@MARKET/MARKET_Pipis/assets/aoSKXXcr_Vigilanties.anim",
        song        = "Kekkaorai.mp3@MARKET/MARKET_Pipis/assets/fmjbR9D5_Kekkaorai.mp3",
        musicName   = "Kekkaorai",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: yao_yi_yao.lua
    {
        name        = "Yao yi yao",
        desc        = "Chinese dance again",
        anim        = "Yaoyiyao.anim@MARKET/MARKET_Pipis/assets/uCoZVKB2_Yaoyiyao.anim",
        song        = "Yaoyiyao.mp3@MARKET/MARKET_Pipis/assets/UztLfPKe_Yaoyiyao.mp3",
        musicName   = "Yaoyiyao",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: lonely_club.lua
    {
        name        = "Lonely club",
        desc        = "What is this animation cro",
        anim        = "LonelyClub.anim@MARKET/MARKET_Pipis/assets/3qMOcM5h_LonelyClub.anim",
        song        = "LonelyClub.mp3@MARKET/MARKET_Pipis/assets/WcgDbHxv_LonelyClub.mp3",
        musicName   = "Lonely Club",
        volume      = 0.8,
        configText  = "No settings.",
    },
}

for i = 1, #dances do
    local d = dances[i]
    table.insert(modules, function()
        local m = {}
        local animator = nil
        local start = 0

        m.ModuleType  = "DANCE"
        m.Name        = d.name
        m.Description = d.desc
        m.Assets      = {d.anim, d.song}

        m.Config = function(parent)
            Util_CreateText(parent, d.configText, 14, Enum.TextXAlignment.Center)
        end

        m.SaveConfig = function() return {} end
        m.LoadConfig = function(save) end

        m.Init = function(figure)
            SetOverrideDanceMusic(AssetGetContentId(d.song:match("^[^@]+")), d.musicName, d.volume)
            animator        = AnimLib.Animator.new()
            animator.rig    = figure
            animator.track = AnimLib.Track.fromfile(AssetGetPathFromFilename(d.anim:match("^[^@]+")))
            animator.looped = true
            animator.speed  = 1
        end

        m.Update = function(dt, figure)
            if animator then
                animator:Step(GetOverrideDanceMusicTime())
            end
        end

        m.Destroy = function(figure)
            animator = nil
        end

        return m
    end)
end

return modules
