-- Generated by KernelPacker
--  0 dance module(s) folded, 2 other module file(s)

local modules = {}


-- Custom modules

-- from: UPDATED meow meow.lua
do
local ok, result = pcall(function()
local modules = {}
table.insert(modules, function()
	local m = {}
	m.ModuleType = "MOVESET"
	m.Name = "Gatito 1x1x1x1"
	m.Description = "JOIN ME- OWWWWWWWWWW!!!\n\nUpdated by Berry/Noelle1!1!!1!1!1!!1, originally by you know who."
	m.InternalName = "Gatito_1x"
	m.Assets = {
		"CatIdle.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/TRnzHzEs_CatIdle.anim",
		"CatWalk.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/vv8bGz4w_CatWalk.anim",
		"CatRun.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/9PBK91vx_CatRun.anim",
		"CatM1.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/RAjxue2d_CatM1.anim",
		"CatMass.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/VfDsD7KY_CatMass.anim",
		"CatKill.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/qGXV4Rf3_CatKill.anim",
		"CatIntro.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/uGDuvZPb_CatIntro.anim",
		"CatShedKill.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/pYyJ2pMN_CatShedKill.anim",
		"CatStunStart.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/sd4V9CJn_CatStunStart.anim",
		"CatStunLoop.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/9u83adWu_CatStunLoop.anim",
		"CatStunEnd.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/IpM3es4r_CatStunEnd.anim",
		"CatVictim.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/er05GBGY_CatVictim.anim",
		"CatShedVictim.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/CAKB3hP0_CatShedVictim.anim",
		"CatEntanglement.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/ALTANFSl_CatEntanglement.anim",
		"CatRotten.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/StcVJ7cN_CatRotten.anim",
		"CatEye.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/m1GQqdES_CatEye.anim",
		"MinionIdle.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/DciuiVkG_MinionIdle.anim",
		"MinionRun.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/w169wMid_MinionRun.anim",
		"MinionAttack.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/5lWCgWgs_MinionAttack.anim",
		"MinionSpawn.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/NM81NAIf_MinionSpawn.anim",
		"MinionWalk.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/BQzJBIfV_MinionWalk.anim",
		"CatM1.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/z9TUJ1XD_CatM1.mp3",
		"Gatito.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/cJ5iv9A7_Gatito.mp3",
		"CatKill.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/KwWnXusm_CatKill.mp3",
		"CatIntro.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/8QTxoYjN_CatIntro.mp3",
		"CatShedKill.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/V2xsRiVU_CatShedKill.mp3",
		"CatStun.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/PR2bQr6o_CatStun.mp3",
		"CatMass.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/LQCybUI7_CatMass.mp3",
		"CatEntangle.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/ArvMdCqY_CatEntangle.mp3",
		"CatRotten.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/sNh9U0Rz_CatRotten.mp3",
		"CatVoice.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/FIykZsyA_CatVoice.mp3",
		"CatEye.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/90X8Jt57_CatEye.mp3",
	}
	m.Config = function(parent) end
	local Players    = game:GetService("Players")
	local Debris     = game:GetService("Debris")
	local UIS        = game:GetService("UserInputService")
	local RunService = game:GetService("RunService")
	local Player     = Players.LocalPlayer
	local animator     = nil
	local tracks       = {}
	local currentTrack = nil
	local animationTime = 0
	local lastState    = "none"
	local usingSkill   = false
	local lastIdleVoice = 0
	local isSprinting  = false
	local flingActive  = false
	local touchConns   = {}
	local figureRef    = nil
	local activeVictims = {}
	local observeConn  = nil
	local inObserveLoop = false
	local observeTarget = nil
	local voidActive   = false
	local voidHit      = false
	local activeMinions = {}
	local minionConns   = {}
	local cachedMinionAppearances = {}
	local appearancesCached       = false
	local function playSound(id, parent)
		local s = Instance.new("Sound")
		s.SoundId = AssetGetContentId(id)
		s.Volume = 1.5
		s.Parent = parent
		s:Play()
		Debris:AddItem(s, 8)
	end
	local function loadAnim(fig, file, looped)
		local a = AnimLib.Animator.new()
		a.rig    = fig
		a.track  = AnimLib.Track.fromfile(AssetGetPathFromFilename(file))
		a.looped = looped or false
		a.speed  = 1
		a.weight = 0
		return a
	end
	local function setupFlingTouched(figure)
		local function hookPart(part)
			local conn = part.Touched:Connect(function(hit)
				if not hit or not hit.Parent then return end
				local target = hit.Parent
				if target:IsA("Accessory") then target = target.Parent end
				if target == figure then return end
				if not target:FindFirstChildOfClass("Humanoid") then return end
				if voidActive then voidHit = true end
				if flingActive then ReanimateFling(target) end
			end)
			table.insert(touchConns, conn)
		end
		for _, part in ipairs(figure:GetDescendants()) do
			if part:IsA("BasePart") then hookPart(part) end
		end
		table.insert(touchConns, figure.DescendantAdded:Connect(function(part)
			if part:IsA("BasePart") then hookPart(part) end
		end))
	end
	local function getRandomPlayer()
		local valid = {}
		for _, p in ipairs(Players:GetPlayers()) do
			if p ~= Player and p.Character and p.Character:FindFirstChild("HumanoidRootPart") then
				table.insert(valid, p)
			end
		end
		if #valid > 0 then return valid[math.random(1, #valid)] end
		return nil
	end
	local function spawnVictimNPC(offsetCFrame, animName, duration)
		if not figureRef then return end
		task.spawn(function()
			local targetPlayer = getRandomPlayer()
			local dummy
			if targetPlayer and targetPlayer.Character then
				pcall(function()
					targetPlayer.Character.Archivable = true
					dummy = targetPlayer.Character:Clone()
					targetPlayer.Character.Archivable = false
				end)
			end
			if not dummy then
				pcall(function()
					figureRef.Archivable = true
					dummy = figureRef:Clone()
					figureRef.Archivable = false
				end)
			end
			if not dummy then
				dummy = Players:CreateHumanoidModelFromDescription(
					Instance.new("HumanoidDescription"),
					Enum.HumanoidRigType.R6
				)
			end
			if not dummy then return end
			dummy.Name = "Meowified"
			dummy.Parent = workspace
			for _, v in ipairs(dummy:GetDescendants()) do
				if v:IsA("Script") or v:IsA("LocalScript") or v:IsA("Sound")
				or v:IsA("ScreenGui") or v:IsA("BillboardGui") or v:IsA("SurfaceGui") then
					v:Destroy()
				elseif v:IsA("BasePart") then
					v.Massless    = true
					v.CanCollide  = false
					v.CanTouch    = false
					v.CanQuery    = false
					if v.Name == "HumanoidRootPart" then
						v.Anchored = true
					else
						v.Anchored = false
					end
				end
			end
			local root   = dummy:FindFirstChild("HumanoidRootPart") or dummy:FindFirstChild("Torso")
			local myRoot = figureRef:FindFirstChild("HumanoidRootPart") or figureRef:FindFirstChild("Torso")
			if root and myRoot then
				if dummy:IsA("Model") then
					dummy.PrimaryPart = root
					dummy:PivotTo(myRoot.CFrame * offsetCFrame)
				else
					root.CFrame = myRoot.CFrame * offsetCFrame
				end
			end
			local ok, dAnim = pcall(function()
				return loadAnim(dummy, animName, false)
			end)
			if ok and dAnim then
				dAnim.weight = 1
				table.insert(activeVictims, {
					anim  = dAnim,
					dummy = dummy,
					start = os.clock()
				})
			end
			Debris:AddItem(dummy, duration + 0.3)
		end)
	end
	local function clearObserve()
		inObserveLoop = false
		observeTarget = nil
		if observeConn then
			observeConn:Disconnect()
			observeConn = nil
		end
	end
	local MINION_CHASE_RADIUS    = 30
	local MINION_CHASE_SPEED     = 8
	local MINION_WANDER_SPEED    = 4
	local MINION_ATTACK_RANGE    = 4
	local MINION_ATTACK_ANIM_DUR = 0.5
	local MINION_ATTACK_COOLDOWN = 1.75
	local MINION_WANDER_RANGE    = 20
	local MINION_WANDER_COOLDOWN = 2.0
	local MINION_SPAWN_OFFSETS = {
		CFrame.new(-4, 0, 0),
		CFrame.new( 4, 0, 0),
		CFrame.new( 0, 0, 4),
	}
	local function getClosestPlayerInRadius(minionRoot, radius)
		local bestDist   = math.huge
		local bestTarget = nil
		for _, p in ipairs(Players:GetPlayers()) do
			if p ~= Player and p.Character then
				local pRoot = p.Character:FindFirstChild("HumanoidRootPart")
				if pRoot then
					local dist = (pRoot.Position - minionRoot.Position).Magnitude
					if dist < radius and dist < bestDist then
						bestDist   = dist
						bestTarget = p
					end
				end
			end
		end
		return bestTarget, bestDist
	end
	local function minionSetAnim(minionData, animKey, looped)
		if minionData.currentAnimKey == animKey then return end
		minionData.currentAnimKey = animKey
		minionData.animator.track  = minionData.tracks[animKey]
		minionData.animator.looped = looped
		minionData.animTime        = 0
	end
	local function pickWanderTarget(minionRoot)
		local base = minionRoot.Position
		local angle = math.random() * math.pi * 2
		local dist  = math.random(5, MINION_WANDER_RANGE)
		return Vector3.new(
			base.X + math.cos(angle) * dist,
			base.Y,
			base.Z + math.sin(angle) * dist
		)
	end
	local function moveMinionToward(minionRoot, targetPos, speed, dt)
		local dir = (targetPos - minionRoot.Position)
		dir = Vector3.new(dir.X, 0, dir.Z)
		local mag = dir.Magnitude
		if mag < 0.5 then return true end
		local step = dir.Unit * speed * dt
		if step.Magnitude > mag then step = dir end
		minionRoot.CFrame = CFrame.new(minionRoot.Position + step, minionRoot.Position + dir.Unit)
		return false
	end
	local function runMinionAI(minionData, dt)
		local root = minionData.model:FindFirstChild("HumanoidRootPart")
		if not root or not minionData.model.Parent then return false end
		local now  = os.clock()
		minionData.animTime = minionData.animTime + dt
		minionData.animator:Step(minionData.animTime)
		if minionData.currentAnimKey == "attack" and not minionData.attackAnimDone then
			local elapsed = now - minionData.attackAnimStart
			if elapsed >= MINION_ATTACK_ANIM_DUR then
				minionData.attackAnimDone  = true
				minionData.onCooldown      = true
				minionData.lastAttackTime  = now
			else
				return true
			end
		end
		if minionData.onCooldown then
			minionSetAnim(minionData, "idle", true)
			if now - minionData.lastAttackTime >= MINION_ATTACK_COOLDOWN then
				minionData.onCooldown     = false
				minionData.attackAnimDone = false
				minionData.wanderTarget   = nil
				minionData.wanderArrivalTime = nil
			end
			return true
		end
		local target, dist = getClosestPlayerInRadius(root, MINION_CHASE_RADIUS)
		if target then
			local pRoot = target.Character and target.Character:FindFirstChild("HumanoidRootPart")
			if not pRoot then return true end
			if dist <= MINION_ATTACK_RANGE then
				if minionData.currentAnimKey ~= "attack" then
					minionSetAnim(minionData, "attack", false)
					minionData.attackAnimStart = now
					minionData.attackAnimDone  = false
					ReanimateFling(target.Character)
				end
			else
				minionSetAnim(minionData, "run", true)
				moveMinionToward(root, pRoot.Position, MINION_CHASE_SPEED, dt)
			end
		else
			if minionData.wanderArrivalTime then
				minionSetAnim(minionData, "idle", true)
				if now - minionData.wanderArrivalTime >= MINION_WANDER_COOLDOWN then
					minionData.wanderArrivalTime = nil
					minionData.wanderTarget      = nil  
				end
				return true
			end
			minionSetAnim(minionData, "walk", true)
			if not minionData.wanderTarget then
				minionData.wanderTarget = pickWanderTarget(root)
			end
			local reached = moveMinionToward(root, minionData.wanderTarget, MINION_WANDER_SPEED, dt)
			if reached then
				minionData.wanderTarget      = nil
				minionData.wanderArrivalTime = now  
			end
		end
		return true
	end
	local function prefetchMinionAppearances(count)
		local appearances = {}  
		local friendIds = {}
		pcall(function()
			local pages = Players:GetFriendsAsync(Player.UserId)
			while true do
				for _, info in ipairs(pages:GetCurrentPage()) do
					table.insert(friendIds, info.Id)
					if #friendIds >= count * 3 then break end  
				end
				if pages.IsFinished or #friendIds >= count * 3 then break end
				pages:AdvanceToNextPageAsync()
			end
		end)
		for i = #friendIds, 2, -1 do
			local j = math.random(1, i)
			friendIds[i], friendIds[j] = friendIds[j], friendIds[i]
		end
		for _, uid in ipairs(friendIds) do
			if #appearances >= count then break end
			local desc
			pcall(function()
				desc = Players:GetHumanoidDescriptionFromUserId(uid)
			end)
			if desc then
				table.insert(appearances, desc)
			end
		end
		if #appearances < count then
			for _, p in ipairs(Players:GetPlayers()) do
				if #appearances >= count then break end
				if p ~= Player then
					local desc
					pcall(function()
						desc = Players:GetHumanoidDescriptionFromUserId(p.UserId)
					end)
					if desc then
						table.insert(appearances, desc)
					end
				end
			end
		end
		while #appearances < count do
			table.insert(appearances, Instance.new("HumanoidDescription"))
		end
		return appearances
	end
	local function buildMinionModel(offsetCFrame, humanoidDesc)
		if not figureRef then return nil end
		local dummy
		if humanoidDesc then
			pcall(function()
				dummy = Players:CreateHumanoidModelFromDescription(
					humanoidDesc,
					Enum.HumanoidRigType.R6
				)
			end)
		end
		if not dummy then
			pcall(function()
				figureRef.Archivable = true
				dummy = figureRef:Clone()
				figureRef.Archivable = false
			end)
		end
		if not dummy then return nil end
		dummy.Name   = "GatitoMinion"
		dummy.Parent = workspace
		for _, v in ipairs(dummy:GetDescendants()) do
			if v:IsA("Script") or v:IsA("LocalScript") or v:IsA("Sound")
			or v:IsA("ScreenGui") or v:IsA("BillboardGui") or v:IsA("SurfaceGui") then
				v:Destroy()
			elseif v:IsA("BasePart") then
				v.Massless   = true
				v.CanCollide = (v.Name == "HumanoidRootPart")
				v.CanTouch   = true
				v.CanQuery   = true
				v.Anchored   = false
			end
		end
		local myRoot = figureRef:FindFirstChild("HumanoidRootPart") or figureRef:FindFirstChild("Torso")
		local dRoot  = dummy:FindFirstChild("HumanoidRootPart") or dummy:FindFirstChild("Torso")
		if myRoot and dRoot then
			if dummy:IsA("Model") then
				dummy.PrimaryPart = dRoot
				dummy:PivotTo(myRoot.CFrame * offsetCFrame)
			else
				dRoot.CFrame = myRoot.CFrame * offsetCFrame
			end
		end
		if dRoot then dRoot.Anchored = true end
		return dummy
	end
	local function spawnOneMinion(offsetIndex, humanoidDesc)
		if not figureRef then return end
		local offset = MINION_SPAWN_OFFSETS[offsetIndex]
		if not offset then return end
		local model = buildMinionModel(offset, humanoidDesc)
		if not model then return end
		local spawnAnim = loadAnim(model, "MinionSpawn.anim", false)
		spawnAnim.weight = 1
		local minionTracks = {
			idle   = AnimLib.Track.fromfile(AssetGetPathFromFilename("MinionIdle.anim")),
			walk   = AnimLib.Track.fromfile(AssetGetPathFromFilename("MinionWalk.anim")),
			run    = AnimLib.Track.fromfile(AssetGetPathFromFilename("MinionRun.anim")),
			attack = AnimLib.Track.fromfile(AssetGetPathFromFilename("MinionAttack.anim")),
		}
		local minionAnim  = AnimLib.Animator.new()
		minionAnim.rig    = model
		minionAnim.track  = minionTracks.idle
		minionAnim.looped = true
		minionAnim.speed  = 1
		minionAnim.weight = 1
		local minionData = {
			model             = model,
			animator          = minionAnim,
			tracks            = minionTracks,
			currentAnimKey    = "idle",
			animTime          = 0,
			wanderTarget      = nil,
			wanderArrivalTime = nil,
			onCooldown        = false,
			lastAttackTime    = 0,
			attackAnimStart   = 0,
			attackAnimDone    = false,
			spawnAnim         = spawnAnim,
			spawnStart        = os.clock(),
			spawnDone         = false,
		}
		table.insert(activeMinions, minionData)
		Debris:AddItem(model, 300)
	end
	local function destroyAllMinions()
		for _, md in ipairs(activeMinions) do
			if md.model and md.model.Parent then
				md.model:Destroy()
			end
		end
		activeMinions = {}
	end
	m.Init = function(figure)
		figureRef = figure
		local hum  = figure:FindFirstChildOfClass("Humanoid")
		local root = figure:FindFirstChild("HumanoidRootPart")
		if not hum or not root then return end
		animator        = AnimLib.Animator.new()
		animator.rig    = figure
		animator.looped = true
		tracks.idle         = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatIdle.anim"))
		tracks.walk         = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatWalk.anim"))
		tracks.run          = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatRun.anim"))
		tracks.m1           = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatM1.anim"))
		tracks.catMass      = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatMass.anim"))
		tracks.kill         = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatKill.anim"))
		tracks.intro        = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatIntro.anim"))
		tracks.shedKill     = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatShedKill.anim"))
		tracks.stunnedStart = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatStunStart.anim"))
		tracks.stunnedLoop  = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatStunLoop.anim"))
		tracks.stunnedEnd   = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatStunEnd.anim"))
		tracks.catEntangle  = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatEntanglement.anim"))
		tracks.catRotten    = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatRotten.anim"))
		tracks.catEye       = AnimLib.Track.fromfile(AssetGetPathFromFilename("CatEye.anim"))
		currentTrack   = tracks.idle
		animator.track = currentTrack
		SetOverrideMovesetMusic(AssetGetContentId("Gatito.mp3"), "HATRED INCARNATE", 1)
		lastIdleVoice = os.clock()
		setupFlingTouched(figure)
		task.spawn(function()
			cachedMinionAppearances = prefetchMinionAppearances(3)
			appearancesCached       = true
		end)
		ContextActions:BindAction("cat_m1", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill  = true
			flingActive = true
			playSound("CatM1.mp3", root)
			currentTrack   = tracks.m1
			animator.track = currentTrack
			animationTime  = 0
			task.wait(0.90)
			flingActive   = false
			usingSkill    = false
			lastState     = "none"
		end, true, Enum.UserInputType.MouseButton1)
		ContextActions:BindAction("cat_mass", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill        = true
			hum.WalkSpeed     = 0
			hum.JumpPower     = 0
			playSound("CatMass.mp3", root)
			currentTrack      = tracks.catMass
			animator.track    = currentTrack
			animationTime     = 0
			task.wait(3.08)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.E)
		ContextActions:BindAction("cat_kill", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("CatKill.mp3", root)
			currentTrack   = tracks.kill
			animator.track = currentTrack
			animationTime  = 0
			spawnVictimNPC(CFrame.new(0,0,0) * CFrame.Angles(0, math.rad(0), 0), "CatVictim.anim", 3.05)
			task.wait(3.05)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.Z)
		ContextActions:BindAction("cat_intro", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("CatIntro.mp3", root)
			currentTrack   = tracks.intro
			animator.track = currentTrack
			animationTime  = 0
			task.wait(3.67)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.One)
		ContextActions:BindAction("cat_shed_kill", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("CatShedKill.mp3", root)
			currentTrack   = tracks.shedKill
			animator.track = currentTrack
			animationTime  = 0
			spawnVictimNPC(CFrame.new(0,0,0) * CFrame.Angles(0, math.rad(0), 0), "CatShedVictim.anim", 4.27)
			task.wait(4.27)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.Two)
		ContextActions:BindAction("cat_stun", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("CatStun.mp3", root)
			currentTrack   = tracks.stunnedStart
			animator.track = currentTrack
			animationTime  = 0
			task.wait(0.92)
			currentTrack   = tracks.stunnedLoop
			animator.track = currentTrack
			animationTime  = 0
			task.wait(1.08)
			currentTrack   = tracks.stunnedEnd
			animator.track = currentTrack
			animationTime  = 0
			task.wait(0.92)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.Three)
		ContextActions:BindAction("cat_entanglement", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			clearObserve()
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("CatEntangle.mp3", root)
			currentTrack   = tracks.catEntangle
			animator.track = currentTrack
			animationTime  = 0
			task.wait(1.67)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.R)
		ContextActions:BindAction("cat_rotten", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("CatRotten.mp3", root)
			currentTrack   = tracks.catRotten
			animator.track = currentTrack
			animationTime  = 0
			destroyAllMinions()
			local minionAppearances
			if appearancesCached and #cachedMinionAppearances >= 3 then
				minionAppearances = cachedMinionAppearances
				task.spawn(function()
					appearancesCached       = false
					cachedMinionAppearances = prefetchMinionAppearances(3)
					appearancesCached       = true
				end)
			else
				minionAppearances = prefetchMinionAppearances(3)
				cachedMinionAppearances = minionAppearances
				appearancesCached       = true
			end
			task.delay(2.05, function()
				if usingSkill then spawnOneMinion(1, minionAppearances[1]) end  
			end)
			task.delay(2.15, function()
				if usingSkill then spawnOneMinion(2, minionAppearances[2]) end  
			end)
			task.delay(2.25, function()
				if usingSkill then spawnOneMinion(3, minionAppearances[3]) end  
			end)
			task.wait(3.48)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.Q)
		ContextActions:BindAction("cat_eye", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill     = true
			hum.WalkSpeed  = 0
			hum.JumpPower  = 0
			playSound("CatEye.mp3", root)
			currentTrack   = tracks.catEye
			animator.track = currentTrack
			animationTime  = 0
			task.wait(1.75)
			usingSkill    = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState     = "none"
		end, true, Enum.KeyCode.T)
		ContextActions:BindAction("cat_sprint", function(_, state)
			if state == Enum.UserInputState.Begin then
				isSprinting = not isSprinting
				ContextActions:SetTitle("cat_sprint", isSprinting and "Walk" or "Sprint")
			end
		end, true, Enum.KeyCode.LeftShift)
		ContextActions:SetTitle("cat_m1",           "M1")
		ContextActions:SetTitle("cat_mass",          "Mass")
		ContextActions:SetTitle("cat_kill",          "Kill")
		ContextActions:SetTitle("cat_intro",         "Intro")
		ContextActions:SetTitle("cat_shed_kill",     "Shed Kill")
		ContextActions:SetTitle("cat_stun",          "Stun")
		ContextActions:SetTitle("cat_entanglement",  "Entangle")
		ContextActions:SetTitle("cat_rotten",        "Rejuvenate")
		ContextActions:SetTitle("cat_eye",           "Unstable")
		ContextActions:SetTitle("cat_sprint",        "Sprint")
		ContextActions:SetPosition("cat_m1",           UDim2.new(1, -70,  1, -70))
		ContextActions:SetPosition("cat_mass",         UDim2.new(1, -140, 1, -70))
		ContextActions:SetPosition("cat_kill",         UDim2.new(1, -210, 1, -70))
		ContextActions:SetPosition("cat_intro",        UDim2.new(1, -280, 1, -70))
		ContextActions:SetPosition("cat_sprint",       UDim2.new(1, -350, 1, -70))
		ContextActions:SetPosition("cat_shed_kill",    UDim2.new(1, -70,  1, -150))
		ContextActions:SetPosition("cat_stun",         UDim2.new(1, -140, 1, -150))
		ContextActions:SetPosition("cat_entanglement", UDim2.new(1, -210, 1, -150))
		ContextActions:SetPosition("cat_rotten",       UDim2.new(1, -280, 1, -150))
		ContextActions:SetPosition("cat_eye",          UDim2.new(1, -350, 1, -150))
	end
	m.Update = function(dt, figure)
		if not animator then return end
		local hum  = figure:FindFirstChildOfClass("Humanoid")
		local root = figure:FindFirstChild("HumanoidRootPart")
		if not hum then return end
		animationTime += dt
		animator:Step(animationTime)
		local now = os.clock()
		for i = #activeVictims, 1, -1 do
			local data = activeVictims[i]
			if data.dummy and data.dummy.Parent then
				data.anim:Step(now - data.start)
			else
				table.remove(activeVictims, i)
			end
		end
		for i = #activeMinions, 1, -1 do
			local md = activeMinions[i]
			if not md.model or not md.model.Parent then
				table.remove(activeMinions, i)
			else
				if not md.spawnDone then
					local elapsed = now - md.spawnStart
					md.spawnAnim:Step(elapsed)
					if elapsed >= 1.6833332777023315 then
						md.spawnDone = true
					end
				else
					runMinionAI(md, dt)
				end
			end
		end
		if usingSkill then return end
		if os.clock() - lastIdleVoice >= 10 then
			lastIdleVoice = os.clock()
			if math.random() <= 0.4 and root then
				playSound("CatVoice.mp3", root)
			end
		end
		local state = "idle"
		if hum.MoveDirection.Magnitude > 0.1 then
			state = isSprinting and "run" or "walk"
		end
		if lastState ~= state then
			animationTime = 0
			lastState     = state
		end
		local newTrack
		if state == "idle" then
			newTrack      = tracks.idle
			hum.WalkSpeed = 8
		elseif state == "walk" then
			newTrack      = tracks.walk
			hum.WalkSpeed = 8
		elseif state == "run" then
			newTrack      = tracks.run
			hum.WalkSpeed = 27.5
		end
		if currentTrack ~= newTrack then
			currentTrack   = newTrack
			animator.track = currentTrack
		end
		animator:Step(animationTime)
	end
	m.Destroy = function()
		clearObserve()
		destroyAllMinions()
		voidActive  = false
		voidHit     = false
		isSprinting = false
		for _, conn in ipairs(touchConns) do conn:Disconnect() end
		table.clear(touchConns)
		for _, data in ipairs(activeVictims) do
			if data.dummy then data.dummy:Destroy() end
		end
		activeVictims = {}
		ContextActions:UnbindAction("cat_m1")
		ContextActions:UnbindAction("cat_mass")
		ContextActions:UnbindAction("cat_kill")
		ContextActions:UnbindAction("cat_intro")
		ContextActions:UnbindAction("cat_shed_kill")
		ContextActions:UnbindAction("cat_stun")
		ContextActions:UnbindAction("cat_entanglement")
		ContextActions:UnbindAction("cat_rotten")
		ContextActions:UnbindAction("cat_eye")
		ContextActions:UnbindAction("cat_sprint")
		animator                = nil
		tracks                  = {}
		currentTrack            = nil
		figureRef               = nil
		flingActive             = false
		usingSkill              = false
		cachedMinionAppearances = {}
		appearancesCached       = false
	end
	return m
end)
return modules

end)
if not ok then
    (warn or print)("[KernelPacker] failed to load UPDATED meow meow.lua: " .. tostring(result))
elseif type(result) == "table" and result ~= modules then
    for _, fn in ipairs(result) do table.insert(modules, fn) end
end
end

-- from: UPDATED mind of him.lua
do
local ok, result = pcall(function()
local modules = {}
table.insert(modules, function()
	local m = {}
	m.ModuleType = "MOVESET"
	m.Name = "ph0nk1dd"
	m.Description = "the mind of him.\n\nUpd4t3d by b3rry/n03ll3!1!!1!1, 0r1g1n4lly by.. d0 1 h4v3 t0 s4y th1s 4g4in?...."
	m.InternalName = "filth_remnant"
	m.Assets = {
		"PHONKIDLE.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/LoKOO0D4_PHONKIDLE.anim",
		"PHONKWALK.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/BI4jwJJ2_PHONKWALK.anim",
		"PHONKRUN.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/h7c4qAtn_PHONKRUN.anim",
		"PHONKM1.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/pelYxgT8_PHONKM1.anim",
		"PHONKCORRUPT.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/ttN7he2H_PHONKCORRUPT.anim",
		"PHONKKILL.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/KUQ6tnYz_PHONKKILL.anim",
		"PHONKINTRO.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/jYtxpMKE_PHONKINTRO.anim",
		"PHONK7N7KILL.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/QVqeZ9ci_PHONK7N7KILL.anim",
		"PHONKSTUNSTART.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/rNeyR43r_PHONKSTUNSTART.anim",
		"PHONKSTUNLOOP.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/OIm5V8u4_PHONKSTUNLOOP.anim",
		"PHONKSTUNEND.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/XOrcoZE5_PHONKSTUNEND.anim",
		"PHONKVICTIM.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/KS7AR9G8_PHONKVICTIM.anim",
		"PHONK7N7VICTIM.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/LKvsEoIg_PHONK7N7VICTIM.anim",
		"PHONKDELIVERY.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/UUaGQsyD_PHONKDELIVERY.anim",
		"PHONKWALKSPEEDSTART.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/6ODjD5ec_PHONKWALKSPEEDSTART.anim",
		"PHONKWALKSPEEDLOOP.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/NbAv86rH_PHONKWALKSPEEDLOOP.anim",
		"PHONKWALKSPEEDHIT.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/FK07ZwcJ_PHONKWALKSPEEDHIT.anim",
		"PHONKWALKSPEEDFAIL.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/ecdUuCmp_PHONKWALKSPEEDFAIL.anim",
		"PhonkMinionSpawnLeft.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/ePyHLAHm_PhonkMinionSpawnLeft.anim",
		"PhonkMinionSpawnRight.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/z7Hv4X3x_PhonkMinionSpawnRight.anim",
		"PhonkMinionIdle.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/xRukdwSf_PhonkMinionIdle.anim",
		"PhonkMinionAttack.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/yVZRl96n_PhonkMinionAttack.anim",
		"PhonkMinionWalk.anim@MARKET/MARKET_GatitoandPh0nk1dd/assets/PuVoSsAh_PhonkMinionWalk.anim",
		"PHONKM1.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/o6CiTvFe_PHONKM1.mp3",
		"PHONKCORRUPT.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/cXpdk7iG_PHONKCORRUPT.mp3",
		"PHONKDELIVERYVOICE.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/Q6n05jdI_PHONKDELIVERYVOICE.mp3",
		"PHONKKILL.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/BWUhdlor_PHONKKILL.mp3",
		"PHONKINTRO.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/fRxWa20b_PHONKINTRO.mp3",
		"PHONK7N7KILL.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/PdcX8luP_PHONK7N7KILL.mp3",
		"PHONK7N7KILLEFFECT.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/fHD8PGHe_PHONK7N7KILLEFFECT.mp3",
		"PHONKSTUN.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/rrmuAyLF_PHONKSTUN.mp3",
		"PHONKWALKSPEEDSTART.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/d8reYgdB_PHONKWALKSPEEDSTART.mp3",
		"PHONKWALKSPEEDLOOP.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/jfpioHVt_PHONKWALKSPEEDLOOP.mp3",
		"PHONKWALKSPEEDHIT.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/cmsPQZU7_PHONKWALKSPEEDHIT.mp3",
		"PHONKWALKSPEEDFAIL.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/e4rFq08u_PHONKWALKSPEEDFAIL.mp3",
		"PHONKDELIVERY.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/WoyIuBaB_PHONKDELIVERY.mp3",
		"Phonk.mp3@MARKET/MARKET_GatitoandPh0nk1dd/assets/EnHTUqcU_Phonk.mp3",
	}
	m.Config = function(parent) end
	local Players = game:GetService("Players")
	local Debris = game:GetService("Debris")
	local UIS = game:GetService("UserInputService")
	local Player = Players.LocalPlayer
	local animator = nil
	local tracks = {}
	local currentTrack = nil
	local animationTime = 0
	local lastState = "none"
	local usingSkill = false
	local isSprinting = false
	local flingActive = false
	local touchConns = {}
	local figureRef = nil
	local activeVictims = {}
	local observeConn = nil
	local inObserveLoop = false
	local observeTarget = nil
	local voidActive = false
	local voidHit = false
	local activeMinions = {}
	local cachedMinionAppearances = {}
	local appearancesCached = false
	local function playSound(id, parent)
		local s = Instance.new("Sound")
		s.SoundId = AssetGetContentId(id)
		s.Volume = 1.5
		s.Parent = parent
		s:Play()
		Debris:AddItem(s, 8)
	end
	local function loadAnim(fig, file, looped)
		local a = AnimLib.Animator.new()
		a.rig = fig
		a.track = AnimLib.Track.fromfile(AssetGetPathFromFilename(file))
		a.looped = looped or false
		a.speed = 1
		a.weight = 0
		return a
	end
	local function setupFlingTouched(figure)
		local function hookPart(part)
			local conn = part.Touched:Connect(function(hit)
				if not hit or not hit.Parent then return end
				local target = hit.Parent
				if target:IsA("Accessory") then target = target.Parent end
				if target == figure then return end
				if not target:FindFirstChildOfClass("Humanoid") then return end
				if voidActive then
					voidHit = true
				end
				if flingActive then
					ReanimateFling(target)
				end
			end)
			table.insert(touchConns, conn)
		end
		for _, part in ipairs(figure:GetDescendants()) do
			if part:IsA("BasePart") then
				hookPart(part)
			end
		end
		table.insert(touchConns, figure.DescendantAdded:Connect(function(part)
			if part:IsA("BasePart") then
				hookPart(part)
			end
		end))
	end
	local function getRandomPlayer()
		local valid = {}
		for _, p in ipairs(Players:GetPlayers()) do
			if p ~= Player and p.Character and p.Character:FindFirstChild("HumanoidRootPart") then
				table.insert(valid, p)
			end
		end
		if #valid > 0 then
			return valid[math.random(1, #valid)]
		end
		return nil
	end
	local function spawnVictimNPC(offsetCFrame, animName, duration)
		if not figureRef then return end
		task.spawn(function()
			local targetPlayer = getRandomPlayer()
			local dummy
			if targetPlayer and targetPlayer.Character then
				pcall(function()
					targetPlayer.Character.Archivable = true
					dummy = targetPlayer.Character:Clone()
					targetPlayer.Character.Archivable = false
				end)
			end
			if not dummy then
				pcall(function()
					figureRef.Archivable = true
					dummy = figureRef:Clone()
					figureRef.Archivable = false
				end)
			end
			if not dummy then
				dummy = Players:CreateHumanoidModelFromDescription(
					Instance.new("HumanoidDescription"),
					Enum.HumanoidRigType.R6
				)
			end
			if not dummy then return end
			dummy.Name = "Phonked"
			dummy.Parent = workspace
			for _, v in ipairs(dummy:GetDescendants()) do
				if v:IsA("Script") or v:IsA("LocalScript") or v:IsA("Sound")
				or v:IsA("ScreenGui") or v:IsA("BillboardGui") or v:IsA("SurfaceGui") then
					v:Destroy()
				elseif v:IsA("BasePart") then
					v.Massless = true
					v.CanCollide = false
					v.CanTouch = false
					v.CanQuery = false
					if v.Name == "HumanoidRootPart" then
						v.Anchored = true
					else
						v.Anchored = false
					end
				end
			end
			local root = dummy:FindFirstChild("HumanoidRootPart") or dummy:FindFirstChild("Torso")
			local myRoot = figureRef:FindFirstChild("HumanoidRootPart") or figureRef:FindFirstChild("Torso")
			if root and myRoot then
				if dummy:IsA("Model") then
					dummy.PrimaryPart = root
					dummy:PivotTo(myRoot.CFrame * offsetCFrame)
				else
					root.CFrame = myRoot.CFrame * offsetCFrame
				end
			end
			local ok, dAnim = pcall(function()
				return loadAnim(dummy, animName, false)
			end)
			if ok and dAnim then
				dAnim.weight = 1
				table.insert(activeVictims, {
					anim = dAnim,
					dummy = dummy,
					start = os.clock()
				})
			end
			Debris:AddItem(dummy, duration + 0.3)
		end)
	end
	local function clearObserve()
		inObserveLoop = false
		observeTarget = nil
		if observeConn then
			observeConn:Disconnect()
			observeConn = nil
		end
	end
	local function prefetchMinionAppearances(count)
		local appearances = {}
		local friendIds = {}
		pcall(function()
			local pages = Players:GetFriendsAsync(Player.UserId)
			while true do
				for _, info in ipairs(pages:GetCurrentPage()) do
					table.insert(friendIds, info.Id)
					if #friendIds >= count * 3 then break end
				end
				if pages.IsFinished or #friendIds >= count * 3 then break end
				pages:AdvanceToNextPageAsync()
			end
		end)
		for i = #friendIds, 2, -1 do
			local j = math.random(1, i)
			friendIds[i], friendIds[j] = friendIds[j], friendIds[i]
		end
		for _, uid in ipairs(friendIds) do
			if #appearances >= count then break end
			local desc
			pcall(function()
				desc = Players:GetHumanoidDescriptionFromUserId(uid)
			end)
			if desc then
				table.insert(appearances, desc)
			end
		end
		if #appearances < count then
			for _, p in ipairs(Players:GetPlayers()) do
				if #appearances >= count then break end
				if p ~= Player then
					local desc
					pcall(function()
						desc = Players:GetHumanoidDescriptionFromUserId(p.UserId)
					end)
					if desc then
						table.insert(appearances, desc)
					end
				end
			end
		end
		while #appearances < count do
			table.insert(appearances, Instance.new("HumanoidDescription"))
		end
		return appearances
	end
	local function buildMinionModel(offsetCFrame, humanoidDesc)
		if not figureRef then return nil end
		local dummy
		if humanoidDesc then
			pcall(function()
				dummy = Players:CreateHumanoidModelFromDescription(
					humanoidDesc,
					Enum.HumanoidRigType.R6
				)
			end)
		end
		if not dummy then
			pcall(function()
				figureRef.Archivable = true
				dummy = figureRef:Clone()
				figureRef.Archivable = false
			end)
		end
		if not dummy then return nil end
		dummy.Name = "Ph0nk"
		dummy.Parent = workspace
		for _, v in ipairs(dummy:GetDescendants()) do
			if v:IsA("Script") or v:IsA("LocalScript") or v:IsA("Sound")
			or v:IsA("ScreenGui") or v:IsA("BillboardGui") or v:IsA("SurfaceGui") then
				v:Destroy()
			elseif v:IsA("BasePart") then
				v.Massless = true
				v.CanCollide = (v.Name == "HumanoidRootPart")
				v.CanTouch = true
				v.CanQuery = true
				v.Anchored = false
			end
		end
		local myRoot = figureRef:FindFirstChild("HumanoidRootPart") or figureRef:FindFirstChild("Torso")
		local dRoot = dummy:FindFirstChild("HumanoidRootPart") or dummy:FindFirstChild("Torso")
		if myRoot and dRoot then
			if dummy:IsA("Model") then
				dummy.PrimaryPart = dRoot
				dummy:PivotTo(myRoot.CFrame * offsetCFrame)
			else
				dRoot.CFrame = myRoot.CFrame * offsetCFrame
			end
		end
		if dRoot then dRoot.Anchored = true end
		return dummy
	end
	local function getClosestPlayer(minionRoot)
		local bestDist = math.huge
		local bestTarget = nil
		for _, p in ipairs(Players:GetPlayers()) do
			if p ~= Player and p.Character then
				local pRoot = p.Character:FindFirstChild("HumanoidRootPart")
				if pRoot then
					local dist = (pRoot.Position - minionRoot.Position).Magnitude
					if dist < bestDist then
						bestDist = dist
						bestTarget = p
					end
				end
			end
		end
		return bestTarget, bestDist
	end
	local function minionSetAnim(minionData, animKey, looped)
		if minionData.currentAnimKey == animKey then return end
		minionData.currentAnimKey = animKey
		minionData.animator.track = minionData.tracks[animKey]
		minionData.animator.looped = looped
		minionData.animTime = 0
	end
	local function moveMinionToward(minionRoot, targetPos, speed, dt)
		local dir = (targetPos - minionRoot.Position)
		dir = Vector3.new(dir.X, 0, dir.Z)
		local mag = dir.Magnitude
		if mag < 0.5 then return true end
		local step = dir.Unit * speed * dt
		if step.Magnitude > mag then step = dir end
		minionRoot.CFrame = CFrame.new(minionRoot.Position + step, minionRoot.Position + dir.Unit)
		return false
	end
	local function runPhonkMinionAI(md, dt)
		local root = md.model:FindFirstChild("HumanoidRootPart")
		if not root or not md.model.Parent then return false end
		local now = os.clock()
		md.animTime = md.animTime + dt
		md.animator:Step(md.animTime)
		if md.isFading then
			md.fadeElapsed = md.fadeElapsed + dt
			local alpha = math.clamp(1 - (md.fadeElapsed / 1.0), 0, 1)
			for _, part in ipairs(md.model:GetDescendants()) do
				if part:IsA("BasePart") then
					part.Transparency = 1 - alpha
				elseif part:IsA("Decal") or part:IsA("Texture") then
					part.Transparency = 1 - alpha
				end
			end
			if md.fadeElapsed >= 1.0 then
				md.model:Destroy()
				return false
			end
			return true
		end
		if md.isAttacking then
			local elapsed = now - md.attackStart
			if elapsed >= 0.5 then
				md.isAttacking = false
				md.isFading = true
				md.fadeElapsed = 0
			end
			return true
		end
		local target, dist = getClosestPlayer(root)
		if target and target.Character then
			local pRoot = target.Character:FindFirstChild("HumanoidRootPart")
			if pRoot then
				if dist <= 4 then
					minionSetAnim(md, "attack", false)
					md.isAttacking = true
					md.attackStart = now
					ReanimateFling(target.Character)
				else
					minionSetAnim(md, "walk", true)
					moveMinionToward(root, pRoot.Position, 8, dt)
				end
			end
		else
			minionSetAnim(md, "idle", true)
		end
		return true
	end
	local function spawnPhonkMinion(side, humanoidDesc)
		if not figureRef then return end
		local offset = (side == "left") and CFrame.new(-4, 0, 0) or CFrame.new(4, 0, 0)
		local animFile = (side == "left") and "PhonkMinionSpawnLeft.anim" or "PhonkMinionSpawnRight.anim"
		local model = buildMinionModel(offset, humanoidDesc)
		if not model then return end
		local spawnAnim = loadAnim(model, animFile, false)
		spawnAnim.weight = 1
		local minionTracks = {
			idle = AnimLib.Track.fromfile(AssetGetPathFromFilename("PhonkMinionIdle.anim")),
			walk = AnimLib.Track.fromfile(AssetGetPathFromFilename("PhonkMinionWalk.anim")),
			attack = AnimLib.Track.fromfile(AssetGetPathFromFilename("PhonkMinionAttack.anim")),
		}
		local minionAnim = AnimLib.Animator.new()
		minionAnim.rig = model
		minionAnim.track = minionTracks.idle
		minionAnim.looped = true
		minionAnim.speed = 1
		minionAnim.weight = 1
		local minionData = {
			model = model,
			animator = minionAnim,
			tracks = minionTracks,
			currentAnimKey = "idle",
			animTime = 0,
			spawnAnim = spawnAnim,
			spawnStart = os.clock(),
			spawnDone = false,
			isAttacking = false,
			attackStart = 0,
			isFading = false,
			fadeElapsed = 0,
		}
		table.insert(activeMinions, minionData)
		Debris:AddItem(model, 300)
	end
	local function destroyAllMinions()
		for _, md in ipairs(activeMinions) do
			if md.model and md.model.Parent then
				md.model:Destroy()
			end
		end
		activeMinions = {}
	end
	m.Init = function(figure)
		figureRef = figure
		local hum = figure:FindFirstChildOfClass("Humanoid")
		local root = figure:FindFirstChild("HumanoidRootPart")
		if not hum or not root then return end
		animator = AnimLib.Animator.new()
		animator.rig = figure
		animator.looped = true
		tracks.idle          = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKIDLE.anim"))
		tracks.walk          = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKWALK.anim"))
		tracks.run           = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKRUN.anim"))
		tracks.m1            = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKM1.anim"))
		tracks.corrupt       = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKCORRUPT.anim"))
		tracks.kill          = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKKILL.anim"))
		tracks.intro         = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKINTRO.anim"))
		tracks["7n7"]        = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONK7N7KILL.anim"))
		tracks.stunnedStart  = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKSTUNSTART.anim"))
		tracks.stunnedLoop   = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKSTUNLOOP.anim"))
		tracks.stunnedEnd    = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKSTUNEND.anim"))
		tracks.delivery      = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKDELIVERY.anim"))
		tracks.walkspeedStart = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKWALKSPEEDSTART.anim"))
		tracks.walkspeedLoop  = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKWALKSPEEDLOOP.anim"))
		tracks.walkspeedHit   = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKWALKSPEEDHIT.anim"))
		tracks.walkspeedFail  = AnimLib.Track.fromfile(AssetGetPathFromFilename("PHONKWALKSPEEDFAIL.anim"))
		currentTrack = tracks.idle
		animator.track = currentTrack
		SetOverrideMovesetMusic(AssetGetContentId("Phonk.mp3"), "READY FOR RUMBLE", 1)
		setupFlingTouched(figure)
		task.spawn(function()
			cachedMinionAppearances = prefetchMinionAppearances(2)
			appearancesCached = true
		end)
		ContextActions:BindAction("phonk_m1", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill = true
			flingActive = true
			playSound("PHONKM1.mp3", root)
			currentTrack = tracks.m1
			animator.track = currentTrack
			animationTime = 0
			task.wait(0.37)
			flingActive = false
			usingSkill = false
			lastState = "none"
		end, true, Enum.UserInputType.MouseButton1)
		ContextActions:BindAction("phonk_corrupt", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill = true
			flingActive = true
         hum.WalkSpeed = 0
			hum.JumpPower = 0
			playSound("PHONKCORRUPT.mp3", root)
			currentTrack = tracks.corrupt
			animator.track = currentTrack
			animationTime = 0
			task.wait(0.77)
			usingSkill = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState = "none"
		end, true, Enum.KeyCode.E)
		ContextActions:BindAction("phonk_kill", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill = true
			hum.WalkSpeed = 0
			hum.JumpPower = 0
			playSound("PHONKKILL.mp3", root)
			currentTrack = tracks.kill
			animator.track = currentTrack
			animationTime = 0
			spawnVictimNPC(
				CFrame.new(0, 0, 0) * CFrame.Angles(0, math.rad(0), 0),
				"PHONKVICTIM.anim",
				2.42
			)
			task.wait(2.42)
			usingSkill = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState = "none"
		end, true, Enum.KeyCode.Z)
		ContextActions:BindAction("phonk_intro", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill = true
			hum.WalkSpeed = 0
			hum.JumpPower = 0
			playSound("PHONKINTRO.mp3", root)
			currentTrack = tracks.intro
			animator.track = currentTrack
			animationTime = 0
			task.wait(3.33)
			usingSkill = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState = "none"
		end, true, Enum.KeyCode.One)
		ContextActions:BindAction("phonk_7n7_kill", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill = true
			hum.WalkSpeed = 0
			hum.JumpPower = 0
			playSound("PHONK7N7KILL.mp3", root)
			playSound("PHONK7N7KILLEFFECT.mp3", root)
			currentTrack = tracks["7n7"]
			animator.track = currentTrack
			animationTime = 0
			spawnVictimNPC(
				CFrame.new(0, 0, 0) * CFrame.Angles(0, math.rad(0), 0),
				"PHONK7N7VICTIM.anim",
				4.03
			)
			task.wait(4.03)
			usingSkill = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState = "none"
		end, true, Enum.KeyCode.Two)
		ContextActions:BindAction("phonk_stun", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill = true
			hum.WalkSpeed = 0
			hum.JumpPower = 0
			playSound("PHONKSTUN.mp3", root)
			currentTrack = tracks.stunnedStart
			animator.track = currentTrack
			animationTime = 0
			task.wait(0.58)
			currentTrack = tracks.stunnedLoop
			animator.track = currentTrack
			animationTime = 0
			task.wait(0.58)
			currentTrack = tracks.stunnedEnd
			animator.track = currentTrack
			animationTime = 0
			task.wait(1.03)
			usingSkill = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState = "none"
		end, true, Enum.KeyCode.Three)
		ContextActions:BindAction("phonk_delivery", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill = true
			hum.WalkSpeed = 0
			hum.JumpPower = 0
			playSound("PHONKDELIVERY.mp3", root)
			playSound("PHONKDELIVERYVOICE.mp3", root)
			currentTrack = tracks.delivery
			animator.track = currentTrack
			animationTime = 0
			destroyAllMinions()
			local minionAppearances
			if appearancesCached and #cachedMinionAppearances >= 2 then
				minionAppearances = cachedMinionAppearances
				task.spawn(function()
					appearancesCached = false
					cachedMinionAppearances = prefetchMinionAppearances(2)
					appearancesCached = true
				end)
			else
				minionAppearances = prefetchMinionAppearances(2)
				cachedMinionAppearances = minionAppearances
				appearancesCached = true
			end
			task.delay(0.90, function()
				if usingSkill then spawnPhonkMinion("left", minionAppearances[1]) end
			end)
			task.delay(1.73, function()
				if usingSkill then spawnPhonkMinion("right", minionAppearances[2]) end
			end)
			task.wait(2.90)
			usingSkill = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState = "none"
		end, true, Enum.KeyCode.R)
		ContextActions:BindAction("phonk_walk", function(_, state)
			if state ~= Enum.UserInputState.Begin or usingSkill then return end
			usingSkill = true
			voidHit = false
			voidActive = false
			hum.WalkSpeed = 0
			hum.JumpPower = 0
			playSound("PHONKWALKSPEEDSTART.mp3", root)
			currentTrack = tracks.walkspeedStart
			animator.track = currentTrack
			animationTime = 0
			task.wait(0.75)
			local loopSnd = Instance.new("Sound")
			loopSnd.SoundId = AssetGetContentId("PHONKWALKSPEEDLOOP.mp3")
			loopSnd.Volume = 1.5
			loopSnd.Looped = true
			loopSnd.Parent = root
			loopSnd:Play()
			currentTrack = tracks.walkspeedLoop
			animator.track = currentTrack
			animationTime = 0
			voidActive = true
			local hrp = figure:FindFirstChild("HumanoidRootPart")
			local startTime = os.clock()
			local lockedDir = hrp and hrp.CFrame.LookVector or Vector3.new(0, 0, -1)
			hum.WalkSpeed = 0
			hum.AutoRotate = false
			local bv = Instance.new("BodyVelocity")
			bv.Velocity = lockedDir * 90
			bv.MaxForce = Vector3.new(1e5, 0, 1e5)
			bv.P = 1e5
			bv.Parent = hrp
			while (os.clock() - startTime < 1.34) and not voidHit and usingSkill do
				task.wait()
			end
			bv:Destroy()
			hum.AutoRotate = true
			hum.WalkSpeed = 0
			voidActive = false
			if loopSnd then
				loopSnd:Stop()
				loopSnd:Destroy()
			end
			if voidHit and usingSkill then
				playSound("PHONKWALKSPEEDHIT.mp3", root)
				currentTrack = tracks.walkspeedHit
				animator.track = currentTrack
				animationTime = 0
				flingActive = true
				task.wait(1.23)
				flingActive = false
			else
				playSound("PHONKWALKSPEEDFAIL.mp3", root)
				currentTrack = tracks.walkspeedFail
				animator.track = currentTrack
				animationTime = 0
				task.wait(0.70)
			end
			usingSkill = false
			hum.WalkSpeed = 8
			hum.JumpPower = 50
			lastState = "none"
		end, true, Enum.KeyCode.Q)
		ContextActions:BindAction("phonk_sprint", function(_, state)
			if state == Enum.UserInputState.Begin then
				isSprinting = not isSprinting
				if isSprinting then
					ContextActions:SetTitle("phonk_sprint", "Walk")
				else
					ContextActions:SetTitle("phonk_sprint", "Sprint")
				end
			end
		end, true, Enum.KeyCode.LeftShift)
		ContextActions:SetTitle("phonk_m1", "M1")
		ContextActions:SetTitle("phonk_corrupt", "Corrupt")
		ContextActions:SetTitle("phonk_kill", "Kill")
		ContextActions:SetTitle("phonk_walk", "Walkspeed")
		ContextActions:SetTitle("phonk_sprint", "Sprint")
		ContextActions:SetTitle("phonk_intro", "Intro")
		ContextActions:SetTitle("phonk_7n7_kill", "7n7Kill")
		ContextActions:SetTitle("phonk_stun", "Stun")
		ContextActions:SetTitle("phonk_delivery", "Delivery")
		ContextActions:SetPosition("phonk_m1", UDim2.new(1, -70, 1, -70))
		ContextActions:SetPosition("phonk_corrupt", UDim2.new(1, -140, 1, -70))
		ContextActions:SetPosition("phonk_kill", UDim2.new(1, -210, 1, -70))
		ContextActions:SetPosition("phonk_walk", UDim2.new(1, -280, 1, -70))
		ContextActions:SetPosition("phonk_sprint", UDim2.new(1, -350, 1, -70))
		ContextActions:SetPosition("phonk_intro", UDim2.new(1, -70, 1, -150))
		ContextActions:SetPosition("phonk_7n7_kill", UDim2.new(1, -140, 1, -150))
		ContextActions:SetPosition("phonk_stun", UDim2.new(1, -210, 1, -150))
		ContextActions:SetPosition("phonk_delivery", UDim2.new(1, -280, 1, -150))
	end
	m.Update = function(dt, figure)
		if not animator then return end
		local hum = figure:FindFirstChildOfClass("Humanoid")
		local root = figure:FindFirstChild("HumanoidRootPart")
		if not hum then return end
		animationTime += dt
		animator:Step(animationTime)
		local now = os.clock()
		for i = #activeVictims, 1, -1 do
			local data = activeVictims[i]
			if data.dummy and data.dummy.Parent then
				data.anim:Step(now - data.start)
			else
				table.remove(activeVictims, i)
			end
		end
		for i = #activeMinions, 1, -1 do
			local md = activeMinions[i]
			if not md.model or not md.model.Parent then
				table.remove(activeMinions, i)
			else
				if not md.spawnDone then
					local elapsed = now - md.spawnStart
					md.spawnAnim:Step(elapsed)
					if elapsed >= 1.0 then
						md.spawnDone = true
					end
				else
					runPhonkMinionAI(md, dt)
				end
			end
		end
		if usingSkill then return end
		local state = "idle"
		if hum.MoveDirection.Magnitude > 0.1 then
			if isSprinting then
				state = "run"
			else
				state = "walk"
			end
		end
		if lastState ~= state then
			animationTime = 0
			lastState = state
		end
		local newTrack
		if state == "idle" then
			newTrack = tracks.idle
			hum.WalkSpeed = 8
		elseif state == "walk" then
			newTrack = tracks.walk
			hum.WalkSpeed = 8
		elseif state == "run" then
			newTrack = tracks.run
			hum.WalkSpeed = 27.5
		end
		if currentTrack ~= newTrack then
			currentTrack = newTrack
			animator.track = currentTrack
		end
		animator:Step(animationTime)
	end
	m.Destroy = function()
		clearObserve()
		destroyAllMinions()
		voidActive = false
		voidHit = false
		isSprinting = false
		for _, conn in ipairs(touchConns) do
			conn:Disconnect()
		end
		table.clear(touchConns)
		for _, data in ipairs(activeVictims) do
			if data.dummy then
				data.dummy:Destroy()
			end
		end
		activeVictims = {}
		ContextActions:UnbindAction("phonk_m1")
		ContextActions:UnbindAction("phonk_corrupt")
		ContextActions:UnbindAction("phonk_kill")
		ContextActions:UnbindAction("phonk_intro")
		ContextActions:UnbindAction("phonk_7n7_kill")
		ContextActions:UnbindAction("phonk_stun")
		ContextActions:UnbindAction("phonk_delivery")
		ContextActions:UnbindAction("phonk_walk")
		ContextActions:UnbindAction("phonk_sprint")
		animator = nil
		tracks = {}
		currentTrack = nil
		figureRef = nil
		flingActive = false
		usingSkill = false
	end
	return m
end)
return modules
end)
if not ok then
    (warn or print)("[KernelPacker] failed to load UPDATED mind of him.lua: " .. tostring(result))
elseif type(result) == "table" and result ~= modules then
    for _, fn in ipairs(result) do table.insert(modules, fn) end
end
end

return modules
