-- Generated by KernelPacker
--  22 modules detected, 0 files kept same but concatenated

local modules = {}

local dances = {
    -- from: 73_days.lua
    {
        name        = "73 days",
        desc        = "Flower actually do that for 73 days?",
        anim        = "72Days.anim@MARKET/MARKET_lenny018577/assets/zveoDSBi_72Days.anim",
        song        = "73days.mp3@MARKET/MARKET_lenny018577/assets/KSheOGjQ_73days.mp3",
        musicName   = "73 days",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: all_nights_forevr.lua
    {
        name        = "All nights forevr",
        desc        = "Lovers and lovers...",
        anim        = "Allnights.anim@MARKET/MARKET_lenny018577/assets/ufL6BNs9_Allnights.anim",
        song        = "Allnights.mp3@MARKET/MARKET_lenny018577/assets/jTjVQ4kf_Allnights.mp3",
        musicName   = "Allnights",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: bass_boosted_73_days.lua
    {
        name        = "Bass boosted 73 days",
        desc        = "(Bass boosted) Flower actually do that for 73 days?",
        anim        = "72Days.anim@MARKET/MARKET_lenny018577/assets/zveoDSBi_72Days.anim",
        song        = "bassboosted73days.mp3@MARKET/MARKET_lenny018577/assets/nprP5QVF_bassboosted73days.mp3",
        musicName   = "bassboosted73days",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: cubibibibism.lua
    {
        name        = "Cubibibibism",
        desc        = "Ni! han!",
        anim        = "Cubibibibism.anim@MARKET/MARKET_lenny018577/assets/x2HbzQSR_Cubibibibism.anim",
        song        = "Cubism.mp3@MARKET/MARKET_lenny018577/assets/UrNl43kc_Cubism.mp3",
        musicName   = "Cubism",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: everyone_get_in_the_car_we_are_leaving_this_town_now!.lua
    {
        name        = "Everyone get in the car we are leaving this town now!",
        desc        = "AHHHHHHHH WHAT THE , IMPOSSIBLE , THIS ISNT THE CAR NOOOOOOOOOOO NOOOOOOOOOO AHHHHHHHHHH HERMIT PURPLEEEEEE",
        anim        = "EVERYONEGETINTHECARWEARELEAVINGTHISTOWNNOWAHHHHHWHATTHEIMPOSSIBLETHISISNTTHECARNOOOOOOONOOOOOOOOOAHHHHHERMITPURPLE.anim@MARKET/MARKET_lenny018577/assets/NrVrj6uv_EVERYONEGETINTHECARWEARELEAVINGTHISTOWNNOWAHHHHHWHATTHEIMPOSSIBLETHISISNTTHECARNOOOOOOONOOOOOOOOOAHHHHHERMITPURPLE.anim",
        song        = "CAR.mp3@MARKET/MARKET_lenny018577/assets/jLaepVJM_CAR.mp3",
        musicName   = "CAR",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: helicopter.lua
    {
        name        = "Helicopter",
        desc        = "SPIN!",
        anim        = "heli.anim@MARKET/MARKET_lenny018577/assets/OhObVuSD_heli.anim",
        song        = "Heli.mp3@MARKET/MARKET_lenny018577/assets/LtOElXEW_Heli.mp3",
        musicName   = "Heli",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: insane_insanity.lua
    {
        name        = "Insane insanity",
        desc        = "Insanity but you are in an asylum",
        anim        = "Doomed.anim@MARKET/MARKET_lenny018577/assets/epdmlxHu_Doomed.anim",
        song        = "Doom.mp3@MARKET/MARKET_lenny018577/assets/6Hylq6Y2_Doom.mp3",
        musicName   = "Doom!",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: LOUDEST73DAYSDANCE.lua
    {
        name        = "Bass boosted 73 days",
        desc        = "(Bass boosted) Flower actually do that for 73 days?",
        anim        = "72Days.anim@MARKET/MARKET_lenny018577/assets/zveoDSBi_72Days.anim",
        song        = "bassboosted73days1.mp3@MARKET/MARKET_lenny018577/assets/bA1USJor_bassboosted73days1.mp3",
        musicName   = "bassboosted73days (1)",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: obsolete_meal.lua
    {
        name        = "Obsolete meal",
        desc        = "EAT. NOW.",
        anim        = "obsolete.anim@MARKET/MARKET_lenny018577/assets/10VcLnYO_obsolete.anim",
        song        = "Obsolete.mp3@MARKET/MARKET_lenny018577/assets/DZ0Mmx7g_Obsolete.mp3",
        musicName   = "Obsolete",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: stuck_in_my_head.lua
    {
        name        = "Stuck in my head",
        desc        = "Music by supxr",
        anim        = "inhead.anim@MARKET/MARKET_lenny018577/assets/2trgnd9o_inhead.anim",
        song        = "inmyhead.mp3@MARKET/MARKET_lenny018577/assets/B09jylBn_inmyhead.mp3",
        musicName   = "inmyhead",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: youremine!!.lua
    {
        name        = "You're MINE!",
        desc        = "This one...Yeah it doesn't have swearing",
        anim        = "Youreminebutsafe.anim@MARKET/MARKET_lenny018577/assets/9kpLybpZ_Youreminebutsafe.anim",
        song        = "Youreminebutsafe.mp3@MARKET/MARKET_lenny018577/assets/0fBaAygs_Youreminebutsafe.mp3",
        musicName   = "Youreminebutsafe",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: that's_what_i_do!.lua
    {
        name        = "That's what I do!",
        desc        = "Axie song and baldi :face-drooling: :durr:",
        anim        = "Thatswhatido.anim@MARKET/MARKET_lenny018577/assets/Qvw3zviY_Thatswhatido.anim",
        song        = "Thatswhatido.mp3@MARKET/MARKET_lenny018577/assets/kf8GoxTn_Thatswhatido.mp3",
        musicName   = "Thatswhatido",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: spit_it_out.lua
    {
        name        = "SPIT IT OUT",
        desc        = "Got something to tell u..Got smth to say- got got got smth to tell u",
        anim        = "SpitItOutGirl.anim@MARKET/MARKET_lenny018577/assets/F6Y37bQV_SpitItOutGirl.anim",
        song        = "SpitItOut.mp3@MARKET/MARKET_lenny018577/assets/eiVEEZUk_SpitItOut.mp3",
        musicName   = "SpitItOut",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: bfdia_9_dance.lua
    {
        name        = "BFDIA 9 dance",
        desc        = "yeahhhh bfdia :DDDDDD",
        anim        = "Bfdiadance.anim@MARKET/MARKET_lenny018577/assets/khcHAkwK_Bfdiadance.anim",
        song        = "HolyReferences.mp3@MARKET/MARKET_lenny018577/assets/nseBNXMi_HolyReferences.mp3",
        musicName   = "HolyReferences",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: nervy.lua
    {
        name        = "Nervy",
        desc        = "Yeah i got nervy",
        anim        = "Nervy.anim@MARKET/MARKET_lenny018577/assets/TBaOCQzH_Nervy.anim",
        song        = "Nerve.mp3@MARKET/MARKET_lenny018577/assets/Yk9r7UBi_Nerve.mp3",
        musicName   = "Nerve",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: overdrive.lua
    {
        name        = "OVERDRIVE",
        desc        = "TOUHOUUUUUUUUUUUUUUU...Idk if thats touhou related",
        anim        = "OVERDRIVEEE.anim@MARKET/MARKET_lenny018577/assets/ZDPpL9YW_OVERDRIVEEE.anim",
        song        = "Overdriven.mp3@MARKET/MARKET_lenny018577/assets/p2l2QYbz_Overdriven.mp3",
        musicName   = "Overdriven",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: dagemei.lua
    {
        name        = "Dagemei",
        desc        = "Dagemei yeah",
        anim        = "Dagemei.anim@MARKET/MARKET_lenny018577/assets/n9ePPBkC_Dagemei.anim",
        song        = "Dagemei.mp3@MARKET/MARKET_lenny018577/assets/KkRH2iPR_Dagemei.mp3",
        musicName   = "Dagemei",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: EPOCHHHHHHHH.lua
    {
        name        = "Epoch meme , yeah thats it cuz yeah",
        desc        = "The living tombstone",
        anim        = "Epoch.anim@MARKET/MARKET_lenny018577/assets/Kt4jqS6G_Epoch.anim",
        song        = "Epoch.mp3@MARKET/MARKET_lenny018577/assets/Lfyr3xOg_Epoch.mp3",
        musicName   = "Epoch",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: hypno_dance_(minion).lua
    {
        name        = "Hypno dance (Minion)",
        desc        = "The minion variant",
        anim        = "HypnoDanceMinion.anim@MARKET/MARKET_lenny018577/assets/wQUai2AS_HypnoDanceMinion.anim",
        song        = "Hypno.mp3@MARKET/MARKET_lenny018577/assets/ahp0n5HV_Hypno.mp3",
        musicName   = "Hypno",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: split!.lua
    {
        name        = "Split!",
        desc        = "Inspo : theo",
        anim        = "SplitDance.anim@MARKET/MARKET_lenny018577/assets/mC5CiZ8T_SplitDance.anim",
        song        = "Splitdance.mp3@MARKET/MARKET_lenny018577/assets/4vaWSN0d_Splitdance.mp3",
        musicName   = "Splitdance",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: Outdoor.lua
    {
        name        = "Outdoor",
        desc        = "Zachz Winner is peak ngl",
        anim        = "Outdoor.anim@MARKET/MARKET_lenny018577/assets/tIdBBBjz_Outdoor.anim",
        song        = "Discloped.mp3@MARKET/MARKET_lenny018577/assets/GzqTsVFE_Discloped.mp3",
        musicName   = "Discloped",
        volume      = 0.8,
        configText  = "No settings.",
    },
    -- from: sunday.lua
    {
        name        = "Sunday",
        desc        = "Sunday morning",
        anim        = "SundayMorning.anim@MARKET/MARKET_lenny018577/assets/ly4un3df_SundayMorning.anim",
        song        = "SundayMorning.mp3@MARKET/MARKET_lenny018577/assets/mcZ4PQ78_SundayMorning.mp3",
        musicName   = "SundayMorning",
        volume      = 0.8,
        configText  = "No settings.",
    },
}

for i = 1, #dances do
    local d = dances[i]
    table.insert(modules, function()
        local m = {}
        local animator = nil
        local start = 0

        m.ModuleType  = "DANCE"
        m.Name        = d.name
        m.Description = d.desc
        m.Assets      = {d.anim, d.song}

        m.Config = function(parent)
            Util_CreateText(parent, d.configText, 14, Enum.TextXAlignment.Center)
        end

        m.SaveConfig = function() return {} end
        m.LoadConfig = function(save) end

        m.Init = function(figure)
            SetOverrideDanceMusic(AssetGetContentId(d.song:match("^[^@]+")), d.musicName, d.volume)
            animator        = AnimLib.Animator.new()
            animator.rig    = figure
            animator.track = AnimLib.Track.fromfile(AssetGetPathFromFilename(d.anim:match("^[^@]+")))
            animator.looped = true
            animator.speed  = 1
        end

        m.Update = function(dt, figure)
            if animator then
                animator:Step(GetOverrideDanceMusicTime())
            end
        end

        m.Destroy = function(figure)
            animator = nil
        end

        return m
    end)
end

return modules
